(function(g){var window=this;'use strict';var iAm=async function(k,F,a){k.K=g.vM(F,a)},Dx=function(k){k.isActive()||k.start()},iD=function(k,F){return F?k.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},fmR=function(k){return g.nE(k)||k.A("web_enable_caption_language_preference_stickiness")},zbk=function(k,F){const a=new g.OR;
a.languageCode=k.languageCode;a.languageName=k.languageName;a.name=k.name;a.displayName=k.displayName;a.kind=k.kind;a.isDefault=!1;a.D=k.D;a.isTranslateable=k.isTranslateable;a.vssId=k.vssId;a.url=k.url;a.translationLanguage=F;k.xtags&&(a.xtags=k.xtags);k.captionId&&(a.captionId=k.captionId);return a},GVL=async function(k,F){k=k+"|"+F;
F=await g.FU();if(!F)throw g.Ax("gct");return(await g.NH(F)).get("captions",k)},bAm=function(k,F,a){GVL(k,F).then(V=>{V&&a(V.trackData,new g.OR(V.metadata))})},fJ=function(k){if(!wYZ.test(k))throw Error("'"+k+"' is not a valid hex color");
k.length==4&&(k=k.replace(kIz,"#$1$1$2$2$3$3"));k=k.toLowerCase();k=parseInt(k.slice(1),16);return[k>>16,k>>8&255,k&255]},Frz=function(){var k={};
let F="suggest_correction"in g.Kt?g.Kt.suggest_correction:"Edit caption";F=F||"";for(let a in k){const V=()=>String(k[a]);
F=F.replace(new RegExp("\\$\\{"+a+"\\}","gi"),V);F=F.replace(new RegExp("\\$"+a,"gi"),V)}return F},z7=function(){return g.G5("yt-player-caption-display-settings")},ajz=function(k,F){let a=g.HZ(k.segments,F);
a>=0||a<0&&(-a-1)%2===1||(a=-a-1,a>0&&F-k.segments[a-1]===1&&a<k.segments.length&&k.segments[a]-F===1?(g.om(k.segments,a),g.om(k.segments,a-1)):a>0&&F-k.segments[a-1]===1?k.segments[a-1]=F:a<k.segments.length&&k.segments[a]-F===1?k.segments[a]=F:(g.eI(k.segments,a,0,F),g.eI(k.segments,a+1,0,F)))},VzQ=function(k){return k.D&&k.D.Z?k.D.Z+k.player.zn()<k.player.getCurrentTime():!1},MzS=function(k,F){if(k.policy.tQ&&k.player.nQ()){var a=g.S8(F,k.policy,{});
a.set("pot",k.player.nQ());a=a.Rx()}else a=g.S8(F,k.policy,{}).Rx();const V={format:"RAW",withCredentials:!0};if(k.policy.Jl){V.method="POST";const X=F.V;X&&Object.keys(X).length>0?V.postBody=g.SG(X,g.SE):V.postBody=(0,g.wP)([120,0])}k.Z&&(V.responseType="arraybuffer");let M=++k.D3;const C=(0,g.L)();k.K=g.$9(a,V,3,100,-1,X=>{X.errorCode==="net.timeout"&&k.player.K6("capnt",{rn:M++})}).then(X=>{if(k.policy.dV&&M%100===1){var U=(0,g.L)();
k.player.K6("caprsp",{rn:M,ms:U-C,kb:(X.xhr.responseText.length/1024).toFixed()})}a:{X=X.xhr;k.wU();if(k.O){var y=!(k.Z?X.response:X.responseText)||X.status>=400;if(U=g.gSB(X)){X=g.S8(k.O,k.policy,{});k.O.DE(X,U);MzS(k,k.O);break a}y?k.player.K6("capfail",{status:X.status}):(g.eF("fcb_r",(0,g.L)(),k.player.getVideoData()?.j||""),U=k.O.HA[0],y=U.Al,k.W!=null&&k.C!==y&&(k.Z?k.W(X.response,(U.startTime+k.player.zn())*1E3):k.W(X.responseText,(U.startTime+k.player.zn())*1E3),k.C=y))}k.O=null;k.K=null}}).d8(X=>
{k.O=null;
k.K=null;k.player.K6("capfail",{rn:M,status:X.xhr?.status})});
k.O=F;ajz(k.V,k.O.HA[0].Al)},CLL=function(k,F){return F!=null&&F in k.K.D?k.K.D[F]:null},skm=function(k,F,a){const V=[];
for(const M in k.K.D){if(!k.K.D.hasOwnProperty(M))continue;const C=k.K.D[M];if(g.Jy(C,a||null)){const X=C.info.captionTrack;X&&X.languageCode===F&&V.push(C)}}return V.length?V[0]:null},U0Z=function(k,F){const a=[];
for(const M in k.K.D){if(!k.K.D.hasOwnProperty(M))continue;var V=k.K.D[M];if(g.Jy(V,F||null)){let C=V.info.id,X=C,U=`.${C}`,y="",n="";if(V=V.info.captionTrack)C=V.languageCode,X=V.displayName,U=V.vssId,y=V.kind,n=V.id;else{{V=C;let u=g.R11.get(V);u==null&&(u=Xxz[V]||Xxz[V.replace(/-/g,"_")],g.R11.set(V,u));V=u}X=V||X}a.push(new g.OR({id:M,languageCode:C,languageName:X,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:U,kind:y,captionId:n}))}}return a},ycB=function(k,F,a,V){let M=F/360*16;
F>=k&&(k=640,V>a*1.3&&(k=480),M=a/k*16);return M},o38=function(k){let F=1+.25*(k.fontSizeIncrement||0);
if(k.offset===0||k.offset===2)F*=.8;return F},n3B=function(k,F){let a="vertical-rl";
k.D.CK===1&&(a="vertical-lr");g.Vb&&(a=a==="vertical-lr"?"tb-lr":"tb-rl");g.t4(F,"-o-writing-mode",a);g.t4(F,"-webkit-writing-mode",a);g.t4(F,"writing-mode",a);g.t4(F,"text-orientation","upright");g.Dz(F,"ytp-vertical-caption");k.K.params.s8===3&&(g.t4(F,"text-orientation",""),g.t4(F,"transform","rotate(180deg)"))},uyL=function(k,F){const a={};
var V=F.background?F.background:k.D.E6.background;if(F.backgroundOpacity!=null||F.background){var M=F.backgroundOpacity!=null?F.backgroundOpacity:k.D.E6.backgroundOpacity;V=fJ(V);a.background="rgba("+V[0]+","+V[1]+","+V[2]+","+M+")";k.Mw&&(a["box-decoration-break"]="clone",a["border-radius"]=`${k.PA/8}px`)}if(F.fontSizeIncrement!=null||F.offset!=null)a["font-size"]=`${k.TL*o38(F)}px`;V=1;M=F.color||k.D.E6.color;if(F.color||F.textOpacity!=null)M=fJ(M),V=F.textOpacity==null?k.D.E6.textOpacity:F.textOpacity,
M="rgba("+M[0]+","+M[1]+","+M[2]+","+V+")",a.color=M,a.fill=M;var C=F.charEdgeStyle;C===0&&(C=void 0);if(C){M=`rgba(34, 34, 34, ${V})`;let y=`rgba(204, 204, 204, ${V})`;F.gP&&(y=M=F.gP);const n=k.TL/16/2,u=Math.max(n,1);var X=Math.max(2*n,1),U=Math.max(3*n,1);const K=Math.max(5*n,1);V=[];switch(C){case 4:for(;U<=K;U+=n)V.push(`${X}px ${X}px ${U}px ${M}`);break;case 1:X=window.devicePixelRatio>=2?.5:1;for(C=u;C<=U;C+=X)V.push(`${C}px ${C}px ${M}`);break;case 2:V.push(`${u}px ${u}px ${y}`);V.push(`-${u}px -${u}px ${M}`);
break;case 3:for(U=0;U<5;U++)V.push(`0 0 ${X}px ${M}`)}a["text-shadow"]=V.join(", ")}M="";switch(F.fontFamily){case 1:M='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:M='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:M='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:M='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:M='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:M=g.Uq()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:M='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}M&&(a["font-family"]=M);M=F.offset;M==null&&(M=k.D.E6.offset);switch(M){case 0:a["vertical-align"]="sub";break;case 2:a["vertical-align"]="super"}F.fontFamily===7&&(a["font-variant"]="small-caps");F.bold&&(a["font-weight"]="bold");F.italic&&(a["font-style"]="italic");F.underline&&
(a["text-decoration"]="underline");F.HM&&(a.visibility="hidden");F.KB===1&&k.O&&(a["text-combine-upright"]="all",a["text-orientation"]="mixed",M=g.Td||g.r7,k.K.params.s8===3?a.transform=M?"rotate(90deg)":"rotate(180deg)":M&&(a.transform="rotate(-90deg)"));if(F.textEmphasis===1||F.textEmphasis===2||F.textEmphasis===3||F.textEmphasis===4||F.textEmphasis===5)if(g.Td)a["font-weight"]="bold";else switch(a["text-emphasis-style"]="filled circle",a["text-emphasis-color"]="currentcolor",a["webkit-text-emphasis"]=
"filled circle",F.textEmphasis){case 4:case 3:a["text-emphasis-position"]="under left";a["webkit-text-emphasis-position"]="under left";break;case 5:case 2:a["text-emphasis-position"]="over right",a["webkit-text-emphasis-position"]="over right"}return a},G7=function(k){k=k.split("px");
return k.length>0?(k=Number(k[0]))?k:0:0},g3I=function(k,F,a){k.QX=k.QX||!!a;
const V={};Object.assign(V,k.D.E6);Object.assign(V,a||F.D);Object.assign(V,k.Eu.E6);(a=!k.T)&&Kr8(k);let M=k.cA&&k.Jl&&g.fz(V,k.Jl)?k.cA:qzX(k,V);const C=typeof F.text==="string",X=C?F.text.split("\n"):[F.text];for(let y=0;y<X.length;y++){var U=y>0||!F.append;const n=X[y];U&&!a?(Kr8(k),M=qzX(k,V)):U&&a&&(a=!1);n&&(M.appendChild(C?g.uv(n):n),C||n.tagName!=="RUBY"||n.childElementCount!==4||g.Td||!g.j6(n.children[2],"text-emphasis")||(U=k.O?"padding-right":"padding-top",g.j6(n.children[2],"text-emphasis-position")&&
(U=k.O?"padding-left":"padding-bottom"),g.s2?g.t4(M,U,"1em"):g.t4(M,U,"0.5em")))}k.Jl=V;k.cA=M;k.C.push(F)},Kr8=function(k){k.T=g.nR("SPAN");
g.t4(k.T,{display:"block"});g.Dz(k.T,"caption-visual-line");k.V.appendChild(k.T)},qzX=function(k,F){const a=g.nR("SPAN");
g.t4(a,{display:"inline-block","white-space":"pre-wrap"});g.t4(a,uyL(k,F));a.classList.add("ytp-caption-segment");k.T.appendChild(a);a.previousElementSibling&&(g.t4(a.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.t4(a,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return a},IjS=function(k,F,a){if(k===255&&F===255||!k&&!F)return{m$:k,
lm:F,result:0};k=TSm[k];F=TSm[F];if(k&128){var V;if(V=!(F&128))V=F,V=a.sz()&&a.lm===V;if(V)return{m$:k,lm:F,result:1}}else if(F&128&&1<=k&&k<=31)return{m$:k,lm:F,result:2};return{m$:k,lm:F,result:3}},Szz=function(k,F,a,V){F===255&&a===255||!F&&!a?(++k.O===45&&k.reset(),k.V.K.clear(),k.Z.K.clear()):(k.O=0,m0z(k.V,F,a,V))},Z$S=function(k,F){k.D.sort((a,V)=>{const M=a.time-V.time;
return M===0?a.order-V.order:M});
for(const a of k.D)k.time=a.time,a.type===0?Szz(k,a.UW,a.gt,F):a.type===1&&k.K&496&&m0z(k.Z,a.UW,a.gt,F);k.D.length=0},Jc8=function(k,F){switch(k){case 0:return e0m[(F&127)-32];
case 1:return d08[F&15];case 2:return PLk[F&31];case 3:return H$X[F&31]}return 0},bD=function(k,F){if(k.style.type===3){var a=0,V=0,M=k.Z.time+0,C="",X="",U=M;
for(var y=1;y<=15;++y){var n=!1;for(var u=V?V:1;u<=32;++u){var K=k.O[y][u];if(K.D!==0){a===0&&(a=y,V=u);n=String.fromCharCode(K.D);var q=K.timestamp;q<M&&(M=q);K.timestamp=U;X&&(C+=X,X="");C+=n;n=!0}if((K.D===0||u===32)&&n){X="\n";break}else if(V&&!n)break}if(a&&!n)break}C&&F.V(a,V,M,U,C)}else for(V=a=0,C=M=k.Z.time+0,X=1;X<=15;++X)for(U="",y=1;y<=32;++y)if(u=k.O[X][y],K=u.D,K!==0&&(a===0&&(a=X,V=y),n=String.fromCharCode(K),q=u.timestamp,q<=M&&(M=q),U+=n,u.reset()),y===32||K===0)U&&F.V(a,V,M,C,U),
M=C,U="",V=a=0},wh=function(k){return k.O[k.row][k.K]},kw=function(k,F,a){F>=2&&k.K>1&&(--k.K,wh(k).D=0);
const V=wh(k);V.timestamp=k.Z.time+0;V.D=Jc8(F,a);k.K<32&&k.K++},Qk8=function(k,F,a,V){for(let X=0;X<V;X++)for(let U=0;U<=32;U++){var M=k.O[F+X][U],C=k.O[a+X][U];
M.D=C.D;M.timestamp=C.timestamp}},FO=function(k,F,a){for(let V=0;V<a;V++)for(let M=0;M<=32;M++)k.O[F+V][M].reset()},aA=function(k){k.row=k.D>0?k.D:1;
k.K=1;FO(k,0,15)},rcB=function(k){k.style.set(1);
k.D=k.V;k.D.D=0;k.D.style=k.style;k.O.mode=1<<k.D.V},VU=function(k,F,a){const V=k.K;
let M=!1;switch(k.style.get()){case 4:case 1:case 2:k.style.get()===4&&V.D>0||(bD(V,a),aA(k.K),aA(k.V),V.row=15,V.D=F,M=!0)}k.style.set(3);k.D=V;k.D.style=k.style;k.O.mode=1<<V.V;M?V.K=1:V.D!==F&&(V.D>F?(bD(V,a),FO(V,V.row-V.D,F)):V.row<F&&(F=V.D),V.D=F)},h0Z=function(k){k.style.set(4);
k.D=k.text;k.D.style=k.style;k.O.mode=1<<k.D.V},m0z=function(k,F,a,V){k.K.update();
F=IjS(F,a,k.K);switch(F.result){case 0:return;case 1:case 2:return}var M=F.m$;F=F.lm;if(32<=M||!M)k.D.mode&k.D.K&&(a=M,a&128&&(a=127),F&128&&(F=127),k=k.V.D,a&96&&kw(k,0,a),F&96&&kw(k,0,F),a!==0&&F!==0&&k.style.type===3&&bD(k,V));else if(M&16)a:if(!k.K.matches(M,F)&&(a=k.K,a.m$=M,a.lm=F,a.state=2,a=M&8?k.C:k.O,k.V=a,k.D.mode=1<<(k.Z<<2)+(a.Z<<1)+(a.style.type===4?1:0),(k.D.mode|1<<(k.Z<<2)+(a.Z<<1)+(a.style.type!==4?1:0))&k.D.K))if(F&64){V=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(M&7)<<1|F>>5&1];
k=F&16?((F&14)>>1)*4:0;F=a.D;switch(a.style.get()){case 4:V=F.row;break;case 3:if(V!==F.row){if(V<F.D&&(V=F.D,V===F.row))break;var C=1+F.row-F.D;const X=1+V-F.D;Qk8(F,X,C,F.D);a=C;M=F.D;X<C?(C=X+M-C,C>0&&(a+=C,M-=C)):(C=C+M-X,C>0&&(M-=C));FO(F,a,M)}}F.row=V;F.K=k+1}else switch(M&7){case 1:switch(F&112){case 32:kw(a.D,0,32);break a;case 48:F===57?(V=a.D,wh(V).D=0,V.K<32&&V.K++):kw(a.D,1,F&15)}break;case 2:F&32&&kw(a.D,2,F&31);break;case 3:F&32&&kw(a.D,3,F&31);break;case 4:case 5:if(32<=F&&F<=47)switch(F){case 32:rcB(a);
break;case 33:V=a.D;V.K>1&&(--V.K,wh(V).D=0);break;case 36:V=a.D;k=wh(V);for(F=0;F<=15;F++)for(a=0;a<=32;a++)if(V.O[F][a]===k){for(;a<=32;a++)V.O[F][a].reset();break}break;case 37:VU(a,2,V);break;case 38:VU(a,3,V);break;case 39:VU(a,4,V);break;case 40:kw(a.D,0,32);break;case 41:V=a;V.style.set(2);V.D=V.K;V.D.D=0;V.D.style=V.style;V.O.mode=1<<V.D.V;break;case 42:V=a;k=V.text;k.D=15;k.style.set(4);aA(k);h0Z(V);break;case 43:h0Z(a);break;case 44:k=a;F=k.K;switch(k.style.get()){case 1:case 2:case 3:bD(F,
V)}FO(F,0,15);break;case 45:b:{F=a;k=F.D;switch(F.style.get()){default:case 2:case 1:break b;case 4:if(k.row<15){++k.row;k.K=1;break b}break;case 3:}k.D<2&&(k.D=2,k.row<k.D&&(k.row=k.D));F=k.row-k.D+1;bD(k,V);Qk8(k,F,F+1,k.D-1);FO(k,k.row,1)}break;case 46:FO(a.V,0,15);break;case 47:k=a,bD(k.K,V),k.V.updateTime(k.O.time+0),V=k.V,k.V=k.K,k.K=V,rcB(k)}break;case 7:switch(F){case 33:case 34:case 35:V=a.D,(V.K+=F&3)>32&&(V.K=32)}}},AcZ=function(k,F,a,V,M,C,X){var U=C[0];
let y=X[U.getAttribute("p")];if(y.I$===1){var n=C[1],u=C[2];C=C[3];U.getAttribute("t");n.getAttribute("t");u.getAttribute("t");C.getAttribute("t");U.getAttribute("p");n.getAttribute("p");C.getAttribute("p");X=X[u.getAttribute("p")];U=x0m(U.textContent,n.textContent,u.textContent,C.textContent,X);return new Mf(k,F,M,a,U,V,y)}switch(y.I$){case 9:case 10:y.textEmphasis=1;break;case 11:y.textEmphasis=2;break;case 12:y.textEmphasis=3;break;case 13:y.textEmphasis=4;break;case 14:y.textEmphasis=5}return new Mf(k,
F,M,a,U.textContent||"",V,y)},x0m=function(k,F,a,V,M){var C=g.Uq();
const X=C?g.nR("DIV"):g.nR("RUBY"),U=g.nR("SPAN");U.textContent=k;X.appendChild(U);k=C?g.nR("DIV"):g.nR("RP");k.textContent=F;X.appendChild(k);F=C?g.nR("DIV"):g.nR("RT");F.textContent=a;X.appendChild(F);a=M.I$;if(a===10||a===11||a===12||a===13||a===14)if(g.t4(F,"text-emphasis-style","filled circle"),g.t4(F,"text-emphasis-color","currentcolor"),g.t4(F,"webkit-text-emphasis","filled circle"),M.I$===11||M.I$===13)g.t4(F,"webkit-text-emphasis-position","under left"),g.t4(F,"text-emphasis-position","under left");
a=!0;if(M.I$===4||M.I$===7||M.I$===12||M.I$===14)g.t4(X,"ruby-position","over"),g.t4(X,"-webkit-ruby-position","before");else if(M.I$===5||M.I$===6||M.I$===11||M.I$===13)g.t4(X,"ruby-position","under"),g.t4(X,"-webkit-ruby-position","after"),a=!1;M=C?g.nR("DIV"):g.nR("RP");M.textContent=V;X.appendChild(M);C&&(V=a,g.t4(X,{display:"inline-block",position:"relative"}),C=X.firstElementChild.nextElementSibling,g.t4(C,"display","none"),C=C.nextElementSibling,g.t4(C,{"font-size":"0.5em","line-height":"1.2em",
"text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.t4(X.lastElementChild,"display","none"),V?(g.t4(X,"padding-top","0.6em"),g.t4(C,"top","0")):(g.t4(X,"padding-bottom","0.6em"),g.t4(C,"bottom","0")));return X},BSC=function(k){const F="_"+Ck++;
return new s7(0,0x8000000000000,0,F,k)},XO=function(k,F){k=k.getAttribute(F);
if(k!=null)return Number(k)},U7=function(k,F){k=k.getAttribute(F);
if(k!=null)return k==="1"},yU=function(k,F){k=XO(k,F);
return k!==void 0?k:null},nk=function(k,F){k=k.getAttribute(F);
if(k!=null)return oA.test(k),k},YzL=function(k,F){const a={},V=F.getAttribute("ws");
Object.assign(a,V?k.X[V]:k.V);k=yU(F,"mh");k!=null&&(a.RT=k);k=yU(F,"ju");k!=null&&(a.textAlign=k);k=yU(F,"pd");k!=null&&(a.s8=k);k=yU(F,"sd");k!=null&&(a.CK=k);k=nk(F,"wfc");k!=null&&(a.windowColor=k);F=XO(F,"wfo");F!==void 0&&(a.windowOpacity=F/255);return a},O$L=function(k,F){const a={},V=F.getAttribute("wp");
V&&Object.assign(a,k.W[V]);k=yU(F,"ap");k!=null&&(a.RZ=k);k=XO(F,"cc");k!=null&&(a.Il=k);k=XO(F,"ah");k!=null&&(a.Z1=k);k=XO(F,"rc");k!=null&&(a.Zb=k);F=XO(F,"av");F!=null&&(a.ew=F);return a},ljX=function(k,F,a,V){let M={};
Object.assign(M,O$L(k,F));Object.assign(M,YzL(k,F));V?g.fz(M,k.V)?(V=k.Z,M=k.V):V="_"+Ck++:V=F.getAttribute("id")||"_"+Ck++;k=XO(F,"t")+a;F=XO(F,"d")||0x8000000000000;if(M.s8===2||M.s8===3)a=M.Zb,M.Zb=M.Il,M.Il=a;return new s7(k,F,0,V,M)},u9=function(k){k=g.Oz(Math.round(k),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-k.length)+k},v3S=function(k,F,a,V,M){V===0&&(V=0x8000000000000);
const C={};F.wpWinPosId&&Object.assign(C,k.V.get(F.wpWinPosId));F.wsWinStyleId&&Object.assign(C,k.Z.get(F.wsWinStyleId));k=F.rcRowCount;k!==void 0&&(C.Zb=k);F=F.ccColCount;F!==void 0&&(C.Il=F);if(C.s8===2||C.s8===3)F=C.Zb,C.Zb=C.Il,C.Il=F;return new s7(a,V,0,M,C)},Kk=function(k){const F=k.byteOffset;
k.byteOffset+=1;return k.D.getUint8(F)},qf=function(k){const F=k.byteOffset;
k.byteOffset+=4;return k.D.getUint32(F)},tzz=function(k){if(typeof k==="string")return!1;
k=new ccZ(k,0);return pxL(k)},pxL=function(k){if(!(k.byteOffset<k.D.byteLength)||qf(k)!==1380139777)return!1;
k.version=Kk(k);if(k.version>1)return!1;Kk(k);Kk(k);Kk(k);return!0},LrC=function(k,F){if(!F)return"";
k.O&&k.K.params.CK!==1&&(F*=-1);return`translate${k.O?"X":"Y"}(${F}px)`},R0L=function(k){k.OO=Array.from(k.element.getElementsByClassName("caption-visual-line"));
for(var F=k.K.params.Zb,a=0,V=0,M=k.OO.length-1;a<F&&M>-1;){var C=k.OO[M];V+=k.O?C.offsetWidth:C.offsetHeight;a++;M--}k.X=V;F=Math;a=F.max;isNaN(k.VX)&&((V=k.D.Il)?(M=g.nR("SPAN"),g.mm(M,"\u2013".repeat(V)),g.t4(M,uyL(k,k.D.E6)),k.V.appendChild(M),k.VX=M.offsetWidth,k.V.removeChild(M)):k.VX=0);V=k.V;k.j=a.call(F,k.VX,k.gB,(k.O?V.offsetHeight:V.offsetWidth)+1)},jkX=function(k,F){R0L(k);
var a=k.OO.reduce((V,M)=>(k.O?M.offsetWidth:M.offsetHeight)+V,0);
a=k.X-a;if(a!==k.a5){const V=a>0&&k.a5===0,M=a<k.a5;F||isNaN(a)||V||!M||(g.Dz(k.element,"ytp-rollup-mode"),k.N(k.element,"transitionend",k.Ml));g.t4(k.V,"transform",LrC(k,a));k.a5=a}R0L(k)},$08=function(k,F){k.D=(a,V)=>{if(a.info.O){var M=a;
if(k.ZE.length>0){for(M=k.ZE.shift();k.ZE.length>0;)M=M.C(k.ZE.shift());M=M.C(a)}if(M){a=M;try{var C=g.BH(a)*1E3}catch(T){C=a.info.startTime*1E3}try{var X=g.XWX(a)*1E3}catch(T){X=a.info.duration*1E3}if(C<0||X<0)C<0&&(C=a.info.startTime*1E3),X<0&&(X=a.info.duration*1E3);a.info.startTime=C/1E3;a.info.V=C/1E3;a.info.duration=X/1E3;a.info.W=X/1E3;const {formatId:U,Al:y,startTimeMs:n,durationMs:u}=k.b6(M);C={formatId:U,startTimeMs:n,durationMs:u,Et:y,nL:y};X=WrX(k.ZW,C.startTimeMs);const K=(a=X>=0?k.ZW[X]:
null)?a.startTimeMs+a.durationMs:0,q=C.startTimeMs+C.durationMs;!a||C.startTimeMs-K>k.K?k.ZW.splice(X+1,0,C):(a.durationMs=Math.max(K,q)-a.startTimeMs,a.nL=Math.max(a.nL,C.nL));V(k.ZW);C=g.hK(M);V=k.O;C=C.buffer.slice(C.byteOffset,C.byteLength+C.byteOffset);M=M.info.V;V.I5?V.W==null?g.re(V.logger,350058965,"Null loaded track meta data at captions data received"):F.rH(C,V.W,M*1E3):g.re(V.logger,350058965,"Null Representation at captions data received")}else g.re(k.logger,350058965,"Empty slice")}else k.ZE.push(a)};
k.J.addEventListener("sabrCaptionsDataLoaded",k.D)},WrX=function(k,F){k=g.HZ(k,{startTimeMs:F},(a,V)=>a.startTimeMs-V.startTimeMs);
return k>=0?k:-k-2},E3z=function(k,F){if(!g.haB(k)||k.D!=null&&g.H8(F,k.D)&&k.D.D.rawcc!=null)return!1;
F=!!k.D&&k.D.isManifestless&&Object.values(k.D.D).some(a=>g.Jy(a,"386"));
k=!!k.D&&!k.D.isManifestless&&g.cPm(k.D);return F||k},NSz=function(k,F,a){const V=[];
for(const M in k.K.D){if(!k.K.D.hasOwnProperty(M))continue;const C=k.K.D[M];if(g.Jy(C,a||null)){const X=C.info.captionTrack;X&&X.languageCode===F&&V.push(C)}}return V.length?V[0]:null},D0k=function(k,F){const a=[];
for(const M in k.K.D){if(!k.K.D.hasOwnProperty(M))continue;var V=k.K.D[M];if(g.Jy(V,F||null)){let C=V.info.id,X=C,U=`.${C}`,y="",n="";if(V=V.info.captionTrack)C=V.languageCode,X=V.displayName,U=V.vssId,y=V.kind,n=V.id;a.push(new g.OR({id:M,languageCode:C,languageName:X,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:U,kind:y,captionId:n}))}}return a},fjX=function(k){const F=i$Q.length;
if(k.byteLength<F)return!1;k=new Uint8Array(k,0,F);for(let a=0;a<F;a++)if(i$Q[a]!==k[a])return!1;return!0},gH=function(k){k=k.split(":");
let F=0;for(const a of k)F=F*60+Number(a);return F*1E3},z0L=function(k,F,a,V){V=Object.assign({RT:0},V);
return new s7(k,F,a,"_"+Ck++,V)},GIm=function(k,F,a,V,M,C,X,U,y){switch(X.tagName){case "b":U.bold=!0;
break;case "i":U.italic=!0;break;case "u":U.underline=!0}for(let u=0;u<X.childNodes.length;u++){var n=X.childNodes[u];if(n.nodeType===3)n=new Mf(F,a,V,M.id,n.nodeValue,C||u>0,g.NL(U)?void 0:U),y.push(n),M.D.push(n);else{const K={};Object.assign(K,U);GIm(k,F,a,V,M,!0,n,K,y)}}},wxZ=function(k,F,a){if(typeof F==="string"||tzz(F))return[{trackData:F,
iZ:a}];if(typeof F==="string"&&F.substring(0,6)==="WEBVTT"||typeof F!=="string"&&fjX(F))return[{trackData:F,iZ:a}];const V=new DataView(F);if(V.byteLength<=8||V.getUint32(4)!==1718909296)return[];var M=g.u21(V);if(k.bI&&M){var C=g.Vw5(M),X=g.Mw9(M);M=M.eW;C&&M&&k.bI.il(M,C,X)}k=g.Os(V,1835295092);if(!k||!k.length||!k[0].size)return[];C=[];for(X=0;X<k.length;X++)M=k[X],M=new Uint8Array(F,M.dataOffset,M.size-(M.dataOffset-M.offset)),M=g.oQ(M),C.push({trackData:M,iZ:a+X*1E3});b$m(V,C,a);return C=C.filter(U=>
!!U.trackData)},FmQ=function(k,F,a){k.D||(k.D=new kJL);
k=k.D.O(F,a);Math.random()<.01&&g.HS(Error("Deprecated subtitles format in web player: WebVTT"));return k},b$m=function(k,F,a){var V=g.xR(k,0,1836476516);
let M=9E4;V&&(M=g.A1(V)||9E4);V=0;const C=g.Os(k,1836019558);for(let U=0;U<C.length;U++){var X=C[U];U<F.length&&(X=g.xR(k,X.dataOffset,1953653094))&&(X=g.xR(k,X.dataOffset,1952867444))&&(X=g.YR(X)/M*1E3,U===0&&(V=X),F[U].iZ=X-V+a||a*U*1E3)}},aNZ=function(k){const F={};
if(k=g.hl(k))F.lang=k,g.UBm.test(k)&&(F.s8=1);return F},V6k=function(k){const F=!!k.J.XX()?.OO();
return k.O==="HLS"&&F?!0:k.TL&&F&&k.O!=="LIVE"&&k.O!=="SABR_LIVE"},IA=function(k,F,a=!1){const V=TK.E6;
k.Z={};Object.assign(k.Z,TK);k.Z.E6={};Object.assign(k.Z.E6,V);k.C={E6:{}};var M=F.backgroundOverride?k.C:k.Z,C=F.background||V.background;oA.test(C);M.E6.background=C;M=F.colorOverride?k.C:k.Z;C=F.color||V.color;oA.test(C);M.E6.color=C;M=F.windowColorOverride?k.C:k.Z;C=F.windowColor||TK.windowColor;oA.test(C);M.windowColor=C;M=F.backgroundOpacityOverride?k.C:k.Z;C=F.backgroundOpacity;C==null&&(C=V.backgroundOpacity);M.E6.backgroundOpacity=C;M=F.fontSizeIncrementOverride?k.C:k.Z;C=F.fontSizeIncrement;
C==null&&(C=V.fontSizeIncrement);M.E6.fontSizeIncrement=C;C=F.fontStyleOverride?k.C:k.Z;M=F.fontStyle;M==null&&(M=V.bold&&V.italic?3:V.bold?1:V.italic?2:0);C=C.E6;switch(M){case 1:C.bold=!0;delete C.italic;break;case 2:delete C.bold;C.italic=!0;break;case 3:C.bold=!0;C.italic=!0;break;default:delete C.bold,delete C.italic}M=F.textOpacityOverride?k.C:k.Z;C=F.textOpacity;C==null&&(C=V.textOpacity);M.E6.textOpacity=C;M=F.windowOpacityOverride?k.C:k.Z;C=F.windowOpacity;C==null&&(C=TK.windowOpacity);M.windowOpacity=
C;M=F.charEdgeStyleOverride?k.C:k.Z;C=F.charEdgeStyle;C==null&&(C=V.charEdgeStyle);M.E6.charEdgeStyle=C;M=F.fontFamilyOverride?k.C:k.Z;C=F.fontFamily;C==null&&(C=V.fontFamily);M.E6.fontFamily=C;k.loaded&&k.yX();a&&g.z5("yt-player-caption-display-settings",F,2592E3)},mN=function(k,F,a){F&&!k.I5?(F=BSC({s8:0,
lang:"en"}),k.I5=[F,new Mf(F.start,F.end-F.start,0,F.id,a??"Captions look like this")],k.player.KL(k.I5)):!F&&k.I5&&(M6I(k,k.I5),k.I5=null)},CvR=function(k){if(!k.J.isInline())return g.G5("yt-player-sticky-caption")},SJ=function(k){let F=void 0;
const a=g.V1().BA(65);if(g.nE(k.B)&&a!=null){if(CvR(k)!=null)return!1;F=!a}return F},syk=function(k){if(k.B.jF===1||k.videoData.yG===1||g.YM(k.videoData,"yt:cc")==="alwayson")return!0;
let F;k.videoData.captionTracks.length&&(F=k.getAudioTrack().K);if(k.B.jF===2){if(g.nE(k.B))var a=CvR(k);else if(k.storage)try{a=k.storage.get("module-enabled")}catch(M){k.storage.remove("module-enabled")}else a=null;if(a!=null)return!!a}a=iD(k.player.getAudioTrack(),g.nE(k.B));const V=g.YM(k.videoData,"yt:cc");if(SJ(k)===void 0){if(a==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return V?V==="on":!0;if(a==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return V==="on"}else return V==="on";return F==="ON"||
g.YM(k.videoData,"yt:cc")==="on"},Zf=function(k,F=!1){if(k.D&&!F||!k.videoData.captionTracks.length)return!1;
k=k.getAudioTrack();return!!k.D||k.K==="FORCED_ON"},XgX=function(k,F){if(k.D){var a=k.J.XX().Zl().textTracks,V=null;
k.O==="HLS"?V=k.D.getId():V=k.D.toString();for(let C=0;C<a.length;C++){var M=a[C];M.id===V&&(F?M.mode!=="showing"&&(M.mode="showing",M=k.D,k.Qe(M,!!M,eJ(k)?"g":k.T?"m":"s")):M.mode==="showing"&&(M.mode="disabled"))}}},eJ=function(k){const F=dH(k);
return!!F&&k.D===F},U$I=function(k,F){if(k.O==="HLS")return!1;
g.Rh(k.videoData)&&(F=!0);F||(F=k.O==="TTS"?!1:k.O==="INNERTUBE"?!1:!0);return F||k.B.A("web_deprecate_always_includes_asr_setting")&&g.nE(k.B)?!0:!!g.V1().BA(66)},dH=function(k){return k.X&&k.X.D},P7=function(k,F){if(!k.K)return null;
if(k.X&&k.X.V)return k.X.V;F=U$I(k,F);F=g.a0(k.K.D,F);let a=null;if(fmR(k.B)){var V=k.J.isInline()?void 0:g.G5("yt-player-caption-sticky-language");var M=[V,k.videoData.captionsLanguagePreference,k.B.captionsLanguagePreference,g.YM(k.videoData,"yt:cc_default_lang")];let U=!1;for(let y=0;y<M.length;y++){const n=M[y];if(n){U=!0;for(var C=0;C<F.length;C++)if(g.hl(F[C])===n)return F[C];for(C=0;C<F.length;C++)if(g.hl(F[C]).split("-")[0]===n.split("-")[0])return F[C]}}if(U&&k.K&&(M=k.K.X,M.length))for(var X of M)if(X.languageCode===
V){a=X;break}}else for(X=[k.videoData.captionsLanguagePreference,k.B.captionsLanguagePreference,g.YM(k.videoData,"yt:cc_default_lang")],V=0;V<X.length;V++)for(M=0;M<F.length;M++)if(g.hl(F[M])===X[V])return F[M];X=null;k.X&&k.X.O&&(X=k.X.O);X||(X=F.find(U=>U.isDefault)||null);
X||(X=F[0]||dH(k));X&&a&&g.hl(X).split("-")[0]!==a.languageCode.split("-")[0]&&(X=zbk(X,a));return X},rH=function(k,F,a){k.loaded&&k.unload();
a!=null&&(k.T=a,k.T&&(g.nE(k.B)?H7(k,!!F):Jm(k,!!F)));F!==null||Zf(k,!0)||k.Qe(F,!!F,k.T?"m":"s");k.D=F;Zf(k)&&(k.D=dH(k));QU(k,k.D??void 0);k.load()},H7=function(k,F){k.J.isInline()||g.z5("yt-player-sticky-caption",F,2592E3)},Jm=function(k,F){if(k.storage)try{k.storage.set("module-enabled",F)}catch(a){}},QU=function(k,F){k.B.A("html5_modify_caption_vss_logging")&&(k.videoData.VW=F)},oiR=function(k,F){var a=k.D3[F.id];
a&&a.K!==F&&(a.dispose(),delete k.D3[F.id],a=null);a||(a=y4B(k,F))&&(k.D3[F.id]=a)},niz=function(k,F){const a=F.windowId;
k.uw[a]||(k.uw[a]=[]);k.uw[a].push(F)},y4B=function(k,F){const a=u0z(k);
if(!a)return null;var V=k.D?g.hl(k.D):null;V&&g.UBm.test(V)&&(F.params.s8=1);var M=k.Yw.getPlayerSize();V=M.height*k.j.height;M=M.width*k.j.width;k.B.playerStyle!=="google-live"||k.Z.isDefault||Object.assign(F.params,k.Z);switch(F.params.RT!=null?F.params.RT:F.D.length>1?1:0){case 1:return new KmC(F,k.Z,k.C,a.width,a.height,M,V,k.B.experiments,k.PA.bind(k),k.J);case 2:return new q2m(F,k.Z,k.C,a.width,a.height,M,V,k.B.experiments,k.PA.bind(k),k.J);default:return new hm(F,k.Z,k.C,a.width,a.height,M,
V,k.B.experiments,k.PA.bind(k),k.J)}},u0z=function(k){let F=k.Yw.getVideoContentRect(!0).height,a=k.Yw.getVideoContentRect(!0).width;
if(!F||!a)return null;F*=k.j.height;a*=k.j.width;return{width:a,height:F}},M6I=function(k,F){k.player.z8(F);
for(const a of F)g.qL(k.QX,a);Dx(k.cA)},giz=function(k,F){if(!k.K)return{};
if(F){g.NL(F)||k.Mp(F.vss_id,"m");if(k.V&&k.O!=="HLS"||!g.H1(F))return;if(g.NL(F)){rH(k,null,!0);return}let V;var a=g.a0(k.K.D,!0);for(let M=0;M<a.length;M++){const C=a[M];C.languageCode!==F.languageCode||V&&(C.languageName!==F.languageName||(C.captionId||"")!==(F.captionId||"")||g.Qd(C)!==F.displayName)||(V=F.translationLanguage?zbk(C,F.translationLanguage):C)}k.d1(F.position);!V||V===k.D&&k.loaded||(F=g.il(),a=g.hl(V),F.length&&a===F[F.length-1]||(F.push(a),g.z5("yt-player-caption-language-preferences",
F)),fmR(k.B)&&!k.J.isInline()&&g.z5("yt-player-caption-sticky-language",a,2592E3),rH(k,V,!0))}else return k.loaded&&k.D&&!eJ(k)?g.rO(k.D):{};return""};
g.lQ.prototype.il=g.aH(65,function(k,F,a){this.K.set(k,{Mn:F,er:a})});
g.vA.prototype.il=g.aH(64,function(k,F,a){this.I5.il(k,F,a)});
g.et.prototype.j=g.aH(63,function(){return!1});
g.et.prototype.V=g.aH(62,function(){});
g.dN.prototype.V=g.aH(61,function(k,F,a){this.wU();F=this.C(k,F);const V=this.sO.S().A("html5_report_captions_ctmp_qoe"),M=(0,g.L)();this.O();iAm(this,F,{format:"RAW",onSuccess:C=>{this.K=null;if(V){var X=(C.responseText.length/1024).toFixed();const U=(0,g.L)();this.videoData.K6("capresp",{ms:U-M,kb:X})}X=C.getResponseHeader&&C.getResponseHeader("Content-Length")?Number(C.getResponseHeader("Content-Length")):0;a.rH(C.responseText,k,void 0,void 0,X)},
onError:V?C=>{this.videoData.K6("capfail",{status:C?.status??0})}:void 0,
withCredentials:!0})});
g.PA.prototype.V=g.aH(60,function(k,F,a){this.wU();F=this.C(k,F);this.O();this.K=g.vM(F,{format:"RAW",onSuccess:V=>{this.K=null;const M=V.getResponseHeader&&V.getResponseHeader("Content-Length")?Number(V.getResponseHeader("Content-Length")):0;a.rH(V.responseText,k,void 0,void 0,M)},
withCredentials:!0})});
g.lp.prototype.T=g.aH(59,function(){const k=g.wS(document,"track",void 0,this.D);for(let F=0;F<k.length;F++)g.TJ(k[F])});
g.pO.prototype.T=g.aH(58,function(){this.mediaElement.T()});
g.lp.prototype.VX=g.aH(57,function(){return!(!this.D.textTracks||!this.D.textTracks.addEventListener)});
g.pO.prototype.VX=g.aH(56,function(){return this.mediaElement.VX()});
g.lp.prototype.OO=g.aH(55,function(){return!!this.D.textTracks});
g.pO.prototype.OO=g.aH(54,function(){return this.mediaElement.OO()});
g.lp.prototype.I5=g.aH(53,function(k){for(let F=0;F<k.length;F++)this.D.appendChild(k[F])});
g.pO.prototype.I5=g.aH(52,function(k){this.mediaElement.I5(k)});
g.f3.prototype.I9=g.aH(40,function(k){return g.YY(this.app,{playerType:void 0}).I9(k)});
g.Fm.prototype.I9=g.aH(39,function(k){return this.lw.BE.I9(k)});
g.uQ.prototype.I9=g.aH(38,function(k){return this.C$().some(F=>F.namespace===k)});
g.An.prototype.I9=g.aH(37,function(){return!1});
g.f3.prototype.Mp=g.aH(35,function(k,F){this.app.R5().Mp(k,F)});
g.Fm.prototype.Mp=g.aH(34,function(k,F){this.lw.Mp(k,F)});
g.U$.prototype.Mp=g.aH(33,function(k,F){k=[k,F];g.Q4(this,g.x_(this.provider),"cfi",k)});
g.nu.prototype.Mp=g.aH(32,function(k,F){this.qoe&&this.qoe.Mp(k,F)});
g.Xm.prototype.Mp=g.aH(31,function(k,F){this.Nw.Mp(k,F)});
g.An.prototype.Mp=g.aH(30,function(){});
g.f3.prototype.Qe=g.aH(29,function(k,F,a){this.app.R5().Qe(k,F,a)});
g.Fm.prototype.Qe=g.aH(28,function(k,F,a){this.lw.Qe(k,F,a)});
g.U$.prototype.Qe=g.aH(27,function(k,F,a){if(this.cA!==k||this.Dl!==F)F=F==="rawcc"?"":F,a=[k,F,this.cA,a],g.Q4(this,g.x_(this.provider),"cfs",a),this.cA=k,this.Dl=F});
g.nu.prototype.Qe=g.aH(26,function(k,F,a){this.qoe&&this.qoe.Qe(k,F,a)});
g.Xm.prototype.Qe=g.aH(25,function(k,F,a){this.Nw.Qe(k,F,a)});
g.An.prototype.Qe=g.aH(24,function(){});
g.p3.prototype.AY=g.aH(3,function(k){return(k=this.O(k))?k.D:0});
g.L3.prototype.AY=g.aH(2,function(){return 0});
var kIz=/#(.)(.)(.)/,wYZ=/^#(?:[0-9a-f]{3}){1,2}$/i,Xxz={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},Tsz={en:"English"},INQ=class extends g.et{constructor(k){super(k);this.K=new Set}Z(k){var F=this.sO.XX();if(F&&F.Zl()){F=F.Zl().textTracks;for(const a of F)a.kind==="subtitles"&&!this.K.has(a.language)&&a.language&&(g.P8(this.D,new g.OR({languageCode:a.language,languageName:a.language,kind:a.kind,id:a.id,displayName:Tsz[a.label]||a.label,vss_id:`.${a.language}`})),this.K.add(a.language))}g.a0(this.D).length>
0&&k.E8()}},m$Q=class{constructor(){this.segments=[]}contains(k){k=g.HZ(this.segments,k);return k>=0||k<0&&(-k-1)%2===1}length(){return this.segments.length/2}},S28=class extends g.GB{constructor(k,F,a,V,M,C){super();this.policy=k;this.player=F;this.UO=a;this.W=V;this.Z=M;this.j=C;this.V=new m$Q;this.C=-1;this.K=this.O=this.D=null;this.D3=0;this.T=new g.La(this.I5,1E3,this);this.events=new g.Ms(this);g.Q(this,this.T);g.Q(this,this.events);this.events.N(F,"SEEK_COMPLETE",this.X);this.X();this.I5()}p6(){super.p6();
this.K&&this.K.cancel()}X(){this.seekTo(this.player.getCurrentTime())}seekTo(k){k-=this.player.zn();const F=this.D;this.D=g.ib(this.UO.C(k).HA);F!==this.D&&this.j&&this.j()}reset(){this.V=new m$Q;this.C=-1;this.K&&(this.K.cancel(),this.K=null)}I5(){this.wU();var k;if(k=this.D!=null)k=this.D,k=k.UO.V(k);if(k&&!this.K&&!(this.D&&this.D.startTime-this.player.getCurrentTime()>30)){k=this.D;k=k.UO.cA(k);const M=k.HA[0];if(this.player.getVideoData()?.enableServerStitchedDai){var F=this.player.jU();if(F){var a=
M.UO.info.id;const C=M.Al;var V=k.HA[0].V;if(this.policy.Jl){if(F=g.LWp(F,V,C,a,3))k.V=F}else if(a=F.g6(V,C,a,3))if(V=2,F.bx.has(C)?V=0:g.C_(F,C)&&(V=1),F=V,F===0)a&&(k.D=new g.tV(a));else if(F===2){this.T.start();VzQ(this)&&this.seekTo(this.player.getCurrentTime());return}}}M.UO.index.jq(M.Al)?(this.V.contains(k.HA[0].Al)||MzS(this,k),this.D=g.ib(k.HA)):VzQ(this)&&this.seekTo(this.player.getCurrentTime())}this.T.start()}},ZRR=class extends g.et{constructor(k,F){super(F);this.K=k;this.J=F;this.W=
null;this.I5=!1;this.logger=new g.Q$("caps");this.D3=g.H8(this.J,this.K)}V(k,F,a){this.O();F=CLL(this,k.getId());F||(F=k.languageCode,F=this.K.isManifestless?skm(this,F,"386"):skm(this,F));if(F){var V=(F.index.AY(F.index.Rr())-F.index.getStartTime(F.index.Rr()))*1E3,M=new g.vMw(this.J.S());this.W=new S28(M,this.J,F,(C,X)=>{a.rH(C,k,X,V)},this.D3||g.Ld(F.info),()=>{this.W&&this.W.reset();
this.I5=!0})}}j(){const k=this.I5;
this.I5=!1;return k}Z(k){var F=this.J.S().A("html5_fallback_if_rawcc_missing");const a=this.K.D.rawcc!=null;if(!this.D3||!a&&F)F=this.K.isManifestless?U0Z(this,"386"):U0Z(this);else{if(!a){g.re(this.logger,386248249,"rawcc used but unavailable");return}F=[new g.OR({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.OR({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(const V of F)g.P8(this.D,
V);k.E8()}O(){this.W&&(this.W.dispose(),this.W=null)}C(){return""}},oA=/^#(?:[0-9a-f]{3}){1,2}$/i;var edQ=["left","right","center","justify"];var hm=class extends g.G{constructor(k,F,a,V,M,C,X,U,y,n){const u=n.isInline()&&!0,K={};Object.assign(K,F);Object.assign(K,k.params);Object.assign(K,a);const q={};Object.assign(q,F.E6);k.params.E6&&Object.assign(q,k.params.E6);Object.assign(q,a.E6);u&&(K.windowOpacity=.6,q.backgroundOpacity=0);K.E6=q;const T=K.s8===1,S=[{U:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}];(U=U.ql("caption_edit_on_hover")&&n.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand)&&
S.unshift({U:"button",G:"caption-edit",L:{tabindex:"0","aria-label":Frz()},Y:[{U:"svg",L:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},Y:[{U:"path",L:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({U:"div",G:"caption-window",L:{id:`${"caption-window"}-${k.id}`,dir:T?"rtl":"ltr",tabindex:"0",lang:K.lang},Y:S});this.C=
[];this.QX=!1;this.K=k;this.Jl=this.cA=null;this.nf=C;this.bP=X;this.T=null;this.maxWidth=C*.96;this.maxHeight=X*.96;this.D=K;this.Eu=a;this.D3=F;this.V=this.Z3("captions-text");this.Mw=this.V.style.getPropertyValue("box-decoration-break")!==""||this.V.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.TL=ycB(V,M,C,X);this.nT=y;U&&(this.Z=this.Z3("caption-edit"),this.N(this.Z,"click",()=>{this.nT()}));
this.type=0;this.PA=this.TL*o38(q);this.yX=u;k=new g.CO(this.element,!0);g.Q(this,k);k.subscribe("dragstart",this.Pl,this);k.subscribe("dragmove",this.wy,this);k.subscribe("dragend",this.Jr,this);this.n6=this.L6=this.vA=this.Yw=0;k="";this.D.windowOpacity&&(k=fJ(this.D.windowColor),k="rgba("+k[0]+","+k[1]+","+k[2]+","+this.D.windowOpacity+")");F={"background-color":k,display:this.D.isVisible===!1?"none":"","text-align":edQ[this.D.textAlign]};this.Mw&&(F["border-radius"]=k?`${this.PA/8}px`:"");(this.O=
this.K.params.s8===2||this.K.params.s8===3)&&n3B(this,this.element);g.t4(this.element,F);u&&this.element.parentElement?.style.setProperty("--caption-window-color",k);switch(this.D.RZ){case 0:case 1:case 2:g.Dz(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Dz(this.element,"ytp-caption-window-bottom")}}Pl(k,F){this.L6=k;this.n6=F;const a=g.bv(this.element,this.element.parentElement);this.Yw=k-a.x;this.vA=F-a.y}wy(k,F){if(k!==this.L6||F!==this.n6){g.Np(this.element,"ytp-dragging")||
g.Dz(this.element,"ytp-dragging");var a=g.kd(this.element);k=k-this.Yw-.02*this.nf;var V=F-this.vA-.02*this.bP,M=(k+a.width/2)/this.maxWidth*3;M=Math.floor(g.Oz(M,0,2));var C=(V+a.height/2)/this.maxHeight*3;C=Math.floor(g.Oz(C,0,2));F=M+C*3;k=(k+M/2*a.width)/this.maxWidth;k=g.Oz(k,0,1)*100;a=(V+C/2*a.height)/this.maxHeight;a=g.Oz(a,0,1)*100;this.K.params.RZ=F;this.K.params.ew=a;this.K.params.Z1=k;this.K.params.isDefault=!1;this.D.RZ=F;this.D.ew=a;this.D.Z1=k;this.D.isDefault=!1;this.D3.RZ=F;this.D3.ew=
a;this.D3.Z1=k;this.D3.isDefault=!1;this.uI()}}Jr(){g.fa(this.element,"ytp-dragging")}uI(){this.W(this.C)}W(k){var F=this.yX?0:Math.min(this.E3(),this.maxWidth),a=this.Dl(),V=this.yX;if(V){var M=getComputedStyle(this.V.parentNode);M=G7(M.borderLeftWidth)+G7(M.borderRightWidth)+G7(M.paddingLeft)+G7(M.paddingRight)}else M=0;const C=M;M="";this.K.params.s8===3&&(M="rotate(180deg)");var X=V?`calc(${"96%"} - ${C}px)`:"96%";g.t4(this.element,{top:0,left:0,right:"",bottom:"",width:F?`${F}px`:"",height:a?
`${a}px`:"","max-width":X,"max-height":X,margin:"",transform:""});this.uw(k);M={transform:M,top:"",left:"",width:F?`${F}px`:"",height:a?`${a}px`:"","max-width":"","max-height":""};var U=this.D.Z1*.96+2;X=this.D.RZ;switch(X){case 0:case 3:case 6:(V=this.D.E6.fontSizeIncrement)&&V>0&&this.D.s8!==2&&this.D.s8!==3&&(U=Math.max(U/(1+V*2),2));M.left=`${U}%`;break;case 1:case 4:case 7:M.left=`${U}%`;U=this.V.offsetWidth;F||U?(F=F||U+1,M.width=`${F}px`,M["margin-left"]=V?`${F/-2-C/2}px`:`${F/-2}px`):M.transform+=
" translateX(-50%)";break;case 2:case 5:case 8:M.right=`${100-U}%`}V=this.D.ew*.96+2;switch(X){case 0:case 1:case 2:M.top=`${V}%`;break;case 3:case 4:case 5:M.top=`${V}%`;(a=a||this.element.clientHeight)?(M.height=`${a}px`,M["margin-top"]=`${a/-2}px`):M.transform+=" translateY(-50%)";break;case 6:case 7:case 8:M.bottom=`${100-V}%`}g.t4(this.element,M);if(this.Z){a=this.V.offsetHeight;V=1;for(F=0;F<k.length;F++)M=k[F],typeof M.text==="string"&&(V+=M.text.split("\n").length-1,M.append||F===0||V++);
a/=V;this.Z.style.height=`${a}px`;this.Z.style.width=`${a}px`;this.element.style.paddingLeft=`${a+5}px`;this.element.style.paddingRight=`${a+5}px`;k=Number(this.element.style.marginLeft.replace("px",""))-a-5;a=Number(this.element.style.marginRight.replace("px",""))-a-5;this.element.style.marginLeft=`${k}px`;this.element.style.marginRight=`${a}px`}}uw(k){let F;for(F=0;F<k.length&&k[F]===this.C[F];F++);if(this.QX||this.C.length>F)F=0,this.QX=!1,this.C=[],this.T=this.Jl=this.cA=null,g.q$(this.V);for(;F<
k.length;F++)g3I(this,k[F])}E3(){return 0}Dl(){return 0}toString(){return super.toString()}};var Pvz=class{constructor(){this.O=this.time=this.mode=this.K=0;this.V=new d$Q(this);this.Z=new d$Q(this);this.D=[];this.clear()}clear(){this.O=this.time=this.mode=0;this.D=[];this.reset()}reset(){this.mode=0;this.V.reset(0);this.Z.reset(1)}},TSm=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],HRk=class{constructor(){this.type=0}set(k){this.type=k}get(){return this.type}},J4k=class{constructor(){this.state=this.lm=this.m$=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}sz(){return this.state!==0}matches(k,F){return this.sz()&&k===this.m$&&F===this.lm}},QyI=class{constructor(){this.timestamp=this.D=0}reset(){this.timestamp=
this.D=0}},xw=class{constructor(k){this.Z=k;this.O=[];this.D=this.K=this.row=0;this.style=new HRk;this.V=0;for(k=0;k<=15;k++){this.O[k]=[];for(let F=0;F<=32;F++)this.O[k][F]=new QyI}}updateTime(k){for(let F=1;F<=15;++F)for(let a=1;a<=32;++a)this.O[F][a].timestamp=k}debugString(){let k="\n";for(let F=1;F<=15;++F){for(let a=1;a<=32;++a){const V=this.O[F][a];k=V.D===0?k+"_":k+String.fromCharCode(V.D)}k+="\n"}return k}reset(k){for(let F=0;F<=15;F++)for(let a=0;a<=32;a++)this.O[F][a].reset();this.V=k;
this.D=0;this.K=this.row=1}},e0m=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],d08=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],PLk=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,
194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],H$X=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],r4B=class{constructor(k){this.O=k;this.Z=0;this.style=new HRk;this.C=new xw(this.O);this.T=new xw(this.O);this.text=new xw(this.O);this.K=this.C;this.V=this.T;this.D=this.K}reset(k,F){this.Z=F;this.style.set(2);this.K=this.C;this.V=this.T;this.D=this.K;const a=(k<<2)+(F<<1);this.C.reset(a);this.T.reset(a);
this.text.reset((k<<2)+(F<<1)+1)}},d$Q=class{constructor(k){this.D=k;this.Z=0;this.O=new r4B(this.D);this.C=new r4B(this.D);this.K=new J4k;this.V=this.O}reset(k){this.Z=k;this.K.clear();this.V=this.O;this.O.reset(k,0);this.C.reset(k,1)}};var hdC=class{V(){}};var Mf=class extends g.rZ{constructor(k,F,a,V,M,C=!1,X=null){super(k,k+F,{priority:a,namespace:"captions"});this.windowId=V;this.text=M;this.append=C;this.D=X}toString(){return super.toString()}};var Am=class extends g.GB{reset(){}};var s7=class extends g.rZ{constructor(k,F,a,V,M){super(k,k+F,{priority:a,namespace:"captions"});this.id=V;this.params=M;this.D=[]}toString(){return super.toString()}},Ck=0;var x$Z=class extends Am{constructor(k){super();this.V=k;this.pens={};this.W={};this.X={};this.Z="_"+Ck++;this.T={};this.K=this.D=null;this.C=!0}reset(){this.T={};this.K=this.D=null;this.C=!0}O(k,F){k=k.firstChild;k.getAttribute("format");F=F||0;Number.isFinite(F);k=Array.from(k.childNodes);for(var a of k)if(a.nodeType===1)switch(a.tagName){case "head":var V=a;break;case "body":var M=a}if(V){V=Array.from(V.childNodes);for(var C of V)if(C.nodeType===1)switch(C.tagName){case "pen":a=C.getAttribute("id");
V=this.pens;k={};var X=C.getAttribute("p");X&&Object.assign(k,this.pens[X]);X=U7(C,"b");X!=null&&(k.bold=X);X=U7(C,"i");X!=null&&(k.italic=X);X=U7(C,"u");X!=null&&(k.underline=X);X=yU(C,"et");X!=null&&(k.charEdgeStyle=X);X=yU(C,"of");X!=null&&(k.offset=X);X=nk(C,"bc");X!=null&&(k.background=X);X=nk(C,"ec");X!=null&&(k.gP=X);X=nk(C,"fc");X!=null&&(k.color=X);X=yU(C,"fs");X!=null&&X!==0&&(k.fontFamily=X);X=XO(C,"sz");X!==void 0&&(k.fontSizeIncrement=X/100-1);X=XO(C,"bo");X!==void 0&&(k.backgroundOpacity=
X/255);X=XO(C,"fo");X!==void 0&&(k.textOpacity=X/255);X=yU(C,"rb");X!=null&&X!==10&&X!==0&&(k.I$=X>10?X-1:X);X=yU(C,"hg");X!=null&&(k.KB=X);V[a]=k;break;case "ws":V=C.getAttribute("id");this.X[V]=YzL(this,C);break;case "wp":V=C.getAttribute("id"),this.W[V]=O$L(this,C)}}if(M){C=[];M=Array.from(M.childNodes);for(J of M)if(J.nodeType===1)switch(J.tagName){case "w":this.D=ljX(this,J,F,!1);(M=this.T[this.D.id])&&M.end>this.D.start&&(M.end=this.D.start);this.T[this.D.id]=this.D;C.push(this.D);break;case "p":var U=
J;k=F;M=[];V=U.getAttribute("w")||this.Z;a=!!U7(U,"a");k=(XO(U,"t")||0)+k;X=XO(U,"d")||5E3;a||(!this.C&&this.K&&this.K.windowId===V&&this.K.end>k&&(this.K.end=k),this.K&&this.K.text==="\n"&&(this.K.text=""));const x=a?6:5;var y=U.getAttribute("p");y=y?this.pens[y]:null;const O=Array.from(U.childNodes);O.length&&(this.C=U.getAttribute("d")!=null);for(U=0;U<O.length;U++){var n=O[U],u=void 0;U>0&&(a=!0);let A;n.nodeType===1&&(A=n);if(A&&A.tagName==="s"){if((n=(n=A.getAttribute("p"))?this.pens[n]:null)&&
n.I$&&(n.I$===1?(n=O.slice(U,U+4),n.length===4&&(u=AcZ(k,X,V,a,x,n,this.pens),U+=3)):u=AcZ(k,X,V,a,x,[A],this.pens)),!u){var K=A;u=k;n=X;var q=V,T=a;const l=K.textContent?K.textContent:"";var S=K.getAttribute("p");S=S?this.pens[S]:null;K=XO(K,"t")||0;u=new Mf(u+K,n-K,x,q,l,T,S)}}else u=new Mf(k,X,x,V,n.textContent||"",a,y);M.push(u);this.K=u}if(M.length>0){M[0].windowId===this.Z&&(this.D=ljX(this,J,F,!0),C.push(this.D));for(const A of M)A.windowId=this.D.id,this.D.D.push(A),C.push(A)}}var J=C}else J=
[];return J}};var A4R=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),Bsz=class extends Am{constructor(k){super();this.C=k;this.D=new Map;this.V=new Map;this.Z=new Map;this.K=new Map}reset(){this.K.clear()}O(k,F){k=JSON.parse(k);if(!k)return[];if(k.pens){var a=k.pens,V=0;for(var M of a){a={};var C=M.pParentId;C&&Object.assign(a,this.D.get(C));M.bAttr&&(a.bold=!0);M.iAttr&&(a.italic=!0);M.uAttr&&(a.underline=!0);C=M.ofOffset;C!=null&&(a.offset=C);M.szPenSize!==void 0&&(a.fontSizeIncrement=M.szPenSize/100-1);
C=M.etEdgeType;C!=null&&(a.charEdgeStyle=C);M.ecEdgeColor!==void 0&&(a.gP=u9(M.ecEdgeColor));C=M.fsFontStyle;C!=null&&C!==0&&(a.fontFamily=C);M.fcForeColor!==void 0&&(a.color=u9(M.fcForeColor));M.foForeAlpha!==void 0&&(a.textOpacity=M.foForeAlpha/255);M.bcBackColor!==void 0&&(a.background=u9(M.bcBackColor));M.boBackAlpha!==void 0&&(a.backgroundOpacity=M.boBackAlpha/255);(C=M.rbRuby)&&C!==10&&(a.I$=C>10?C-1:C,a.textEmphasis=A4R.get(a.I$));M.hgHorizGroup&&(a.KB=M.hgHorizGroup);this.D.set(V++,a)}}if(k.wsWinStyles){V=
k.wsWinStyles;M=0;for(var X of V)V={},(a=X.wsParentId)?Object.assign(V,this.Z.get(a)):Object.assign(V,this.C),X.mhModeHint!==void 0&&(V.RT=X.mhModeHint),X.juJustifCode!==void 0&&(V.textAlign=X.juJustifCode),X.pdPrintDir!==void 0&&(V.s8=X.pdPrintDir),X.sdScrollDir!==void 0&&(V.CK=X.sdScrollDir),X.wfcWinFillColor!==void 0&&(V.windowColor=u9(X.wfcWinFillColor)),X.wfoWinFillAlpha!==void 0&&(V.windowOpacity=X.wfoWinFillAlpha/255),this.Z.set(M++,V)}if(k.wpWinPositions){M=k.wpWinPositions;X=0;for(var U of M)M=
{},(V=U.wpParentId)&&Object.assign(M,this.V.get(V)),U.ahHorPos!==void 0&&(M.Z1=U.ahHorPos),U.apPoint!==void 0&&(M.RZ=U.apPoint),U.avVerPos!==void 0&&(M.ew=U.avVerPos),U.ccCols!==void 0&&(M.Il=U.ccCols),U.rcRows!==void 0&&(M.Zb=U.rcRows),this.V.set(X++,M)}if(k.events){k=k.events;U=[];for(const t of k)if(X=(t.tStartMs||0)+F,M=t.dDurationMs||0,t.id)V=String(t.id),k=v3S(this,t,X,M,V),U.push(k),this.K.set(V,k);else{t.wWinId?V=t.wWinId.toString():(V="_"+Ck++,k=v3S(this,t,X,M,V),U.push(k),this.K.set(V,k));
k=U;var y=t;M===0&&(M=5E3);a=this.K.get(V);const M7=(C=!!y.aAppend)?6:5,X9=y.segs;let LQ=null;y.pPenId&&(LQ=this.D.get(y.pPenId));for(y=0;y<X9.length;y++){var n=X9[y],u=n.utf8;if(u){var K=n.tOffsetMs||0;let Sf=null;n.pPenId&&(Sf=this.D.get(n.pPenId));if((a.params.RT!=null?a.params.RT:a.D.length>1?1:0)===2&&C&&u==="\n")continue;n=null;var q=[],T;if(T=Sf&&Sf.I$===1)a:{T=X9;var S=y;if(S+3>=T.length||!T[S+1].pPenId||!T[S+2].pPenId||!T[S+3].pPenId){T=!1;break a}var J=T[S+1].pPenId;(J=this.D.get(J))&&J.I$&&
J.I$===2?(J=T[S+2].pPenId,J=this.D.get(J),!J||!J.I$||J.I$<3?T=!1:(J=T[S+3].pPenId,T=(J=this.D.get(J))&&J.I$&&J.I$===2?!0:!1)):T=!1}if(T)K=X9[y+1].utf8,n=X9[y+3].utf8,T=X9[y+2].utf8,S=this.D.get(X9[y+2].pPenId),u=x0m(u,K,T,n,S),n=new Mf(X,M,M7,V,u,C,Sf),y+=3;else{if(u.indexOf("<")>-1){q=Sf;T=LQ;S=X;J=M;var x=K,O=M7,A=C;const RH=[];var l=g.MP(`<html>${u}</html>`);if(!l.getElementsByTagName("parsererror").length&&l.firstChild?.childNodes.length)for(const zm of l.firstChild.childNodes){l=zm.textContent?.replace(/\n/g,
"")??"";if(zm.nodeType===3&&(!l||l.match(/^ *$/)!=null))continue;const hB={};Object.assign(hB,q||T);switch(zm?.tagName){case "b":hB.bold=!0;break;case "i":hB.italic=!0;break;case "u":hB.underline=!0}RH.push(new Mf(S+x,J-x,O,a.id,l,A,hB))}q=RH}q.length||(q=[new Mf(X+K,M-K,M7,a.id,u,C,Sf||LQ)])}if(q.length)for(const RH of q)k.push(RH),a.D.push(RH);else n&&(k.push(n),a.D.push(n))}C=!0}}F=U}else F=[];return F}};var Y2Q=class extends g.et{constructor(k,F,a){super(k);this.videoData=F;this.audioTrack=a;this.X=F.oH}V(k,F,a){bAm(this.videoData.videoId,k.vssId,a.rH)}Z(k){if(this.audioTrack)for(const F of this.audioTrack.captionTracks)g.P8(this.D,F);k.E8()}};var KmC=class extends hm{constructor(k,F,a,V,M,C,X,U,y,n){super(k,F,a,V,M,C,X,U,y,n);this.type=1}uw(k){const F=this.K.D;super.uw(k);let a,V;for(k=k.length;k<F.length;k++){const M=F[k];let C;V&&M.D===a?C=V:(C={},Object.assign(C,M.D),Object.assign(C,ORI),a=M.D,V=C);g3I(this,M,C)}}},ORI={HM:!0};var ccZ=class extends hdC{constructor(k,F){super();this.trackData=k;this.C=F;this.version=this.Z=this.O=this.byteOffset=0;this.K=[];this.D=new DataView(this.trackData)}V(k,F,a,V,M){if(a<V){const C="_"+Ck++;a=a/1E3-this.C;V=V/1E3-this.C;k=new s7(a,V-a,5,C,{textAlign:0,RZ:0,Z1:F*2.5,ew:k*5.33});M=new Mf(a,V-a,5,C,M);this.K.push(k);this.K.push(M)}}},lNR=class extends Am{constructor(k,F){super();this.K=k;this.V=F;this.track=this.V.languageName==="CC3"?4:0;this.D=new Pvz;this.D.K=1<<this.track}O(k){k=
new ccZ(k,this.K);if(pxL(k)){for(;k.byteOffset<k.D.byteLength;)for(k.version===0?k.O=qf(k)*(1E3/45):k.version===1&&(k.O=qf(k)*4294967296+qf(k)),k.Z=Kk(k);k.Z>0;k.Z--){var F=Kk(k);const a=Kk(k),V=Kk(k);F&4&&(F&3)===this.track&&(this.track===0||this.track===1)&&(F=this.D,F.D.push({time:k.O,type:this.track,UW:a,gt:V,order:F.D.length}))}Z$S(this.D,k);return k.K}return[]}reset(){this.D.clear()}};var q2m=class extends hm{constructor(k,F,a,V,M,C,X,U,y,n){super(k,F,a,V,M,C,X,U,y,n);this.type=2;this.OO=[];this.j=this.X=this.a5=0;this.VX=NaN;this.gB=0;this.Ra=null;this.dB=new g.La(this.Ml,433,this);this.Z&&(n.createClientVe(this.Z,this,167342),this.N(this.Z,"click",()=>{n.logClick(this.Z)}),k=new g.CO(this.element,!0),g.Q(this,k),k.subscribe("hoverstart",()=>{n.logVisibility(this.Z,!0)},this));
g.Dz(this.element,"ytp-caption-window-rollup");g.Q(this,this.dB);g.t4(this.element,"overflow","hidden")}uI(){g.RK(this.dB)}Ml(){this.element.removeEventListener("transitionend",this.Ml,!1);g.fa(this.element,"ytp-rollup-mode");this.W(this.Ra,!0)}Dl(){return this.O?this.j:this.X}E3(){return this.O?this.X:this.j}W(k,F){this.Ra=k;if(this.K.params.Zb){var a=0;for(let V=0;V<this.C.length&&a<k.length;V++)this.C[V]===k[a]&&a++;a>0&&a<k.length&&(k=this.C.concat(k.slice(a)));this.gB=this.j;this.X=this.j=0;
super.W(k);jkX(this,F)}super.W(k)}};var vik=class{constructor(k,F,a,V){this.J=k;this.O=F;this.logger=a;this.rB=V;this.ZW=[];this.ZE=[];this.D=null;this.Yh={V_w:()=>this.D,
l4:()=>this.ZW};
k=g.o6(this.J.S().experiments,"html5_override_micro_discontinuities_threshold_ms");this.K=k>0?k:10}unload(){this.D!=null&&(this.J.removeEventListener("sabrCaptionsDataLoaded",this.D),this.D=null);this.ZW=[];this.J.publish("sabrCaptionsBufferedRangesUpdated",this.ZW)}b6(k){return{formatId:g.jE(k.info.UO.info,this.rB),Al:k.info.Al+(this.rB?0:1),startTimeMs:k.info.V*1E3,durationMs:k.info.W*1E3}}};var c4I=class extends g.et{constructor(k,F){super(F);this.K=k;this.J=F;this.logger=new g.Q$("caps");this.W=this.I5=null;this.D3=new vik(this.J,this,this.logger,this.K.rB)}V(k,F,a){this.O();F=k.getId();F=F!=null&&F in this.K.D?this.K.D[F]:null;F||(F=k.languageCode,F=this.K.isManifestless?NSz(this,F,"386"):NSz(this,F));F&&(this.W=k,this.I5=F,$08(this.D3,a),this.J.publish("sabrCaptionsTrackChanged",g.jE(F.info,this.K.rB)))}Z(k){var F=this.K.isManifestless?D0k(this,"386"):D0k(this);for(const a of F)g.P8(this.D,
a);k.E8()}O(){this.W&&(this.W=this.I5=null,this.D3.unload(),this.J.publish("sabrCaptionsTrackChanged",null))}C(){return""}};var i$Q="WEBVTT".split("").map(k=>k.charCodeAt(0)),kJL=class extends Am{constructor(){super()}O(k,F){k instanceof ArrayBuffer&&(k=g.oQ(new Uint8Array(k)));
const a=[];k=k.split(pgm);for(let S=1;S<k.length;S++){var V=k[S],M=F;if(V!==""&&!t6m.test(V)){var C=B7.exec(V);if(C&&C.length>=4){var X=gH(C[1]),U=gH(C[2])-X;X+=M;var y=(C=C[3])?C.split(" "):[];C={};var n=null;var u="";var K=null,q="";for(const J of y){y=J.split(":");if(y.length!==2)continue;var T=y[1];switch(y[0]){case "line":y=T.split(",");y[0].endsWith("%")&&(n=y[0],C.ew=Number.parseInt(n,10),y.length===2&&(u=y[1].trim()));break;case "position":y=T.split(",");K=y[0];C.Z1=Number.parseInt(K,10);
y.length===2&&(q=y[1].trim());break;case "align":switch(T){case "start":C.textAlign=0;break;case "middle":C.textAlign=2;break;case "end":C.textAlign=1}}}n||u||(u="end");if(!K)switch(C.textAlign){case 0:C.Z1=0;break;case 1:C.Z1=100;break;case 2:C.Z1=50}if(C.textAlign!=null){n=0;switch(u){case "center":n+=3;break;case "end":n+=6;break;default:n+=0}switch(q){case "line-left":n+=0;break;case "center":n+=1;break;case "line-right":n+=2;break;default:switch(C.textAlign){case 0:n+=0;break;case 2:n+=1;break;
case 1:n+=2}}u=n<0||n>8?7:n;C.RZ=u}V=V.substring(B7.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");q=C;C=V;V={};if(C.indexOf("<")<0&&C.indexOf("&")<0)M=z0L(X,U,5,q),U=new Mf(X,U,5,M.id,C,!1,g.NL(V)?void 0:V),a.push(M),a.push(U),M.D.push(U);else for(u=C.split(Lmz),u.length===1?(C=5,q=z0L(X,U,C,q)):(n=C=6,q=Object.assign({Il:32},q),q=new s7(X,U,n,"_"+Ck++,q)),a.push(q),n=X,K=0;K<u.length;K++)if(y=u[K],K%2===0){T=g.MP(`<html>${y}</html>`);let J;T.getElementsByTagName("parsererror").length?(J=T.createElement("span"),
J.appendChild(T.createTextNode(y))):J=T.firstChild;GIm(this,n,U-(n-X),C,q,K>0,J,V,a)}else n=gH(y)+M}B7.lastIndex=0}}return a}},t6m=/^NOTE/,pgm=/(?:\r\n|\r|\n){2,}/,B7=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Lmz=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var Rd8=class extends g.GB{constructor(k,F){super();this.J=k;this.B=F;this.D=null;this.bI=this.J.jU();this.logger=new g.Q$("caps")}clear(){this.D&&this.D.dispose();this.D=null}reset(){this.D&&this.D.reset()}p6(){super.p6();this.clear()}};var TK={windowColor:"#080808",windowOpacity:0,textAlign:2,RZ:7,Z1:50,ew:100,isDefault:!0,E6:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.dp("captions",class extends g.ZH{constructor(k){super(k);this.J=k;this.QX=[];this.D3={};this.uw={};this.T=!1;this.O="NONE";this.K=this.X=this.I5=this.a5=this.L6=null;this.vA={E8:()=>{this.E8()},
rH:(V,M,C,X,U=0)=>{const y=Number(this.videoData.S().wB().D.BA(g.O35)??0);U>0&&y>0&&this.videoData.lengthSeconds>0&&U/this.videoData.lengthSeconds>y?this.J.K6("tts",{dropcap:U}):this.rH(V,M,C,X)}};
this.D=null;this.B=this.J.S();this.videoData=this.J.getVideoData();this.Yw=this.J.j4();this.Z={E6:{}};this.C={E6:{}};this.videoData.uI()?this.O="OFFLINE":g.$km(this.videoData,this.J)?this.O="HLS":E3z(this.videoData,this.J)?this.O="SABR_LIVE":g.Eo7(this.videoData,this.J)?this.O="LIVE":this.videoData.captionTracks.length?this.O="INNERTUBE":this.videoData.gB&&(this.O="TTS");this.TL=this.B.controlsType==="3";this.Ml=new Rd8(this.J,this.B);this.OO=new g.Ms(this);this.W=new g.G({U:"div",G:"ytp-caption-window-container",
L:{id:"ytp-caption-window-container"}});this.j={top:0,right:0,bottom:0,left:0,width:1,height:1};let F=null;const a=g.Od("yt-html5-player-modules::subtitlesModuleData");a&&(F=new g.SS(a));this.storage=F;this.n6=!!k.XX()?.VX();this.V=V6k(this);this.VX=!this.V&&this.TL&&this.n6&&(this.O==="LIVE"||this.O==="SABR_LIVE");g.Q(this,this.Ml);this.V?this.Jl=this.cA=null:(this.cA=new g.co(this.E3,void 0,this),g.Q(this,this.cA),this.Jl=new g.La(this.Mw,2E3,this),g.Q(this,this.Jl));g.Q(this,this.OO);g.Ii(this.player,
this.W.element,4);g.Q(this,this.W);this.V||this.OO.N(k,"resize",this.yX);(this.Dl=g.zM(this.B)&&!g.p8()&&!this.J.isFullscreen()&&!this.V&&!this.VX)&&this.OO.N(k,"resize",this.gB);this.OO.N(k,"onPlaybackAudioChange",this.iI);this.OO.N(k,g.oO("captions"),V=>{this.onCueRangeEnter(V)});
this.OO.N(k,g.nX("captions"),V=>{this.onCueRangeExit(V)});
IA(this,z7()||{});g.kj(this.player,"onCaptionsModuleAvailable");this.O==="HLS"&&this.V&&(k=this.J.XX().Zl(),this.n6&&this.OO.N(k.textTracks,"addtrack",this.uI))}p6(){if(this.V||this.VX){const k=this.J.XX();k&&!k.wU()&&k.T()}else mN(this,!1);super.p6()}Id(){return this.B.A("html5_honor_caption_availabilities_in_audio_track")&&this.O!=="LIVE"&&this.O!=="SABR_LIVE"}iR(){if(this.TL)return this.V||this.VX;if(this.O==="HLS")return this.V;var k=this.getAudioTrack();if(this.Id()){if(!k.captionTracks.length)return!1;
if(!this.K)return!0}k=iD(k,g.nE(this.B));return k==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:k==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?Zf(this):SJ(this)||Zf(this)?!0:syk(this)}load(){super.load();this.X=this.getAudioTrack();if(this.K)this.D&&(this.Ml.clear(),this.V?XgX(this,!0):this.player.getPresentingPlayerType()!==3&&this.K.V(this.D,"json3",this.vA),this.O!=="HLS"&&this.V||this.VX||eJ(this)||g.kj(this.player,"captionschanged",g.rO(this.D)));else{let k;this.O==="OFFLINE"?k=new Y2Q(this.player,this.videoData,
this.getAudioTrack()):this.O==="SABR_LIVE"?k=new c4I(this.videoData.D,this.player):this.O==="HLS"?k=new INQ(this.player):this.O==="LIVE"?k=new ZRR(this.videoData.D,this.player):this.O==="INNERTUBE"?k=new g.dN(this.player,this.videoData,this.getAudioTrack()):k=new g.PA(this.player,this.videoData.gB,this.videoData.videoId,g.BL1(this.videoData),this.videoData.eJ,this.videoData.eventId);this.K=k;g.Q(this,this.K);this.K.Z(this.vA)}}unload(){this.V&&this.D?XgX(this,!1):(this.Jl&&this.Jl.fg(),this.player.Cv("captions"),
this.QX=[],this.K&&this.K.O(),this.Ml.clear(),this.I5&&this.player.KL(this.I5),this.yX());super.unload();this.player.sY();g.kj(this.player,"captionschanged",{})}create(){this.iR()&&this.load();var k;a:{if(this.B.A("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(k=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(const F of k)if(F.kind==="asr"&&F.languageCode===
"en"){k=!0;break a}k=!1}k&&this.J.publish("showpromotooltip",this.W.element)}E8(){var k=iD(this.player.getAudioTrack(),g.nE(this.B));var F=k==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?P7(this,this.T):k==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&Zf(this)?dH(this):SJ(this)||this.T||syk(this)?P7(this,this.T):Zf(this)?dH(this):null;if(this.O!=="HLS"&&this.V||this.VX){const a=g.a0(this.K.D,!0);k=[];for(let V=0;V<a.length;V++){const M=a[V],C=g.nR("TRACK");C.setAttribute("kind","subtitles");C.setAttribute("label",
g.Qd(M));C.setAttribute("srclang",g.hl(M));C.setAttribute("id",M.toString());this.VX||C.setAttribute("src",this.K.C(M,"vtt"));M===F&&C.setAttribute("default","1");k.push(C)}F=this.J.XX();F.I5(k);k=F.Zl();this.n6&&this.OO.N(k.textTracks,"change",this.dB)}else!this.D&&F&&rH(this,F),g.kj(this.player,"onCaptionsTrackListChanged"),g.Fx(this.player,"onApiChange")}getTrackById(k){const F=g.a0(this.K.D,!0);for(let a=0;a<F.length;a++)if(F[a].toString()===k)return F[a];return null}dB(){const k=this.J.XX().Zl().textTracks;
let F=null;for(let a=0;a<k.length;a++)k[a].mode==="showing"&&(F=this.getTrackById(k[a].id));(this.loaded?this.D:null)!==F&&rH(this,F,!0)}uI(){this.K?.Z(this.vA)}T5(){!this.D&&this.V||this.unload()}rH(k,F,a,V){if(k){QU(this,this.D??void 0);this.K.j()&&(this.QX=[],this.J.Cv("captions"),Dx(this.cA),this.Ml.reset());a:{var M=this.Ml;V=V||0;a=wxZ(M,k,a||0);k=[];try{for(const O of a){const A=O.trackData,l=O.iZ,t=M.B.A("safari_live_drm_captions_fix");if(typeof A!=="string"){a=k;var C=a.concat;if(t&&fjX(A))var X=
FmQ(M,A,l);else{var U=M,y=F,n=A,u=l,K=V;if(!tzz(n))throw Error("Invalid binary caption track data");U.D||(U.D=new lNR(K,y));X=U.D.O(n,u)}var q=C.call(a,X)}else{if(A.substring(0,6)==="WEBVTT")var T=k.concat(FmQ(M,A,l));else{a=k;var S=a.concat;b:{y=M;U=F;if(A[0]==="{")try{y.D||(y.D=new Bsz(aNZ(U)));var J=y.D.O(A,l);break b}catch(LQ){g.W(LQ);J=[];break b}const M7=g.MP(A);if(!M7||!M7.firstChild){const LQ=Error("Invalid caption track data");LQ.params=A;throw LQ;}if(M7.firstChild.tagName==="timedtext"){if(Number(M7.firstChild.getAttribute("format"))===
3){n=M7;y.D||(y.D=new x$Z(aNZ(U)));J=y.D.O(n,l);break b}const LQ=Error("Unsupported subtitles format in web player (Format2)");LQ.params=A;throw LQ;}if(M7.firstChild.tagName==="transcript"){const LQ=Error("Unsupported subtitles format in web player (Format1)");LQ.params=A;throw LQ;}const X9=Error("Invalid caption track data");X9.params=A;throw X9;}T=S.call(a,J)}q=T}k=q}var x=k;break a}catch(O){g.re(M.logger,187101178,`Captions parsing failed: ${O.message}. `);M.clear();x=[];break a}x=void 0}F=x;F.length>
0&&(x=this.D,this.Qe(x,!!x,eJ(this)?"g":this.T?"m":"s"));this.player.KL(F,void 0,this.O==="LIVE"||this.O==="SABR_LIVE");!this.T||this.VX||eJ(this)||g.Gr(this.B)||g.fj(this.B)||g.R4(this.B)||this.B.D3==="shortspage"||this.player.isInline()||(this.Jl.fg(),F=BSC({RZ:0,Z1:5,ew:5,Zb:2,textAlign:0,s8:0,lang:"en"}),this.a5=[F],x=["Click "," for settings"],this.L6||(M=new g.eW(g.S4()),g.Q(this,M),this.L6=M.element),M=F.end-F.start,(q=g.Qd(this.D))&&this.a5.push(new Mf(F.start,M,0,F.id,q)),this.a5.push(new Mf(F.start,
M,0,F.id,x[0]),new Mf(F.start,M,0,F.id,this.L6,!0),new Mf(F.start,M,0,F.id,x[1],!0)),this.player.KL(this.a5),this.Jl.Wl());!this.T||this.VX||eJ(this)||(g.nE(this.B)?H7(this,!0):Jm(this,!0),this.X&&(this.X.V=this.D),this.player.sY());this.T=!1}}onCueRangeEnter(k){this.QX.push(k);Dx(this.cA)}onCueRangeExit(k){g.qL(this.QX,k);this.K instanceof ZRR&&this.K.D3&&this.player.z8([k]);Dx(this.cA)}getCaptionWindowContainerId(){return this.W.element.id}Mw(){M6I(this,this.a5);this.a5=null}E3(){if(!this.Dl||!this.V){this.cA.stop();
g.DC(this.uw);this.QX.sort(g.yV);var k=this.QX;if(this.I5){const F=g.Gm(k,function(a){return this.I5.indexOf(a)===-1},this);
F.length&&(k=F)}for(const F of k)F instanceof s7?oiR(this,F):niz(this,F);for(const [F,a]of Object.entries(this.D3)){const V=F,M=a;this.uw[V]?(M.element.parentNode||(M instanceof q2m||M instanceof KmC||g.lR(this.D3,(C,X)=>{X!==V&&C.K.params.RZ===M.K.params.RZ&&C.K.params.Z1===M.K.params.Z1&&C.K.params.ew===M.K.params.ew&&(C.dispose(),delete this.D3[X]);return X===V},this),this.W.element.appendChild(M.element)),M.W(this.uw[V])):(M.dispose(),delete this.D3[V])}}}Ac(){IA(this,{},!0);
g.kj(this.player,"captionssettingschanged")}WM(){var k=TK.E6;k={background:k.background,backgroundOpacity:k.backgroundOpacity,charEdgeStyle:k.charEdgeStyle,color:k.color,fontFamily:k.fontFamily,fontSizeIncrement:k.fontSizeIncrement,fontStyle:k.bold&&k.italic?3:k.bold?1:k.italic?2:0,textOpacity:k.textOpacity,windowColor:TK.windowColor,windowOpacity:TK.windowOpacity};const F=z7()||{};F.background!=null&&(k.background=F.background);F.backgroundOverride!=null&&(k.backgroundOverride=F.backgroundOverride);
F.backgroundOpacity!=null&&(k.backgroundOpacity=F.backgroundOpacity);F.backgroundOpacityOverride!=null&&(k.backgroundOpacityOverride=F.backgroundOpacityOverride);F.charEdgeStyle!=null&&(k.charEdgeStyle=F.charEdgeStyle);F.charEdgeStyleOverride!=null&&(k.charEdgeStyleOverride=F.charEdgeStyleOverride);F.color!=null&&(k.color=F.color);F.colorOverride!=null&&(k.colorOverride=F.colorOverride);F.fontFamily!=null&&(k.fontFamily=F.fontFamily);F.fontFamilyOverride!=null&&(k.fontFamilyOverride=F.fontFamilyOverride);
F.fontSizeIncrement!=null&&(k.fontSizeIncrement=F.fontSizeIncrement);F.fontSizeIncrementOverride!=null&&(k.fontSizeIncrementOverride=F.fontSizeIncrementOverride);F.fontStyle!=null&&(k.fontStyle=F.fontStyle);F.fontStyleOverride!=null&&(k.fontStyleOverride=F.fontStyleOverride);F.textOpacity!=null&&(k.textOpacity=F.textOpacity);F.textOpacityOverride!=null&&(k.textOpacityOverride=F.textOpacityOverride);F.windowColor!=null&&(k.windowColor=F.windowColor);F.windowColorOverride!=null&&(k.windowColorOverride=
F.windowColorOverride);F.windowOpacity!=null&&(k.windowOpacity=F.windowOpacity);F.windowOpacityOverride!=null&&(k.windowOpacityOverride=F.windowOpacityOverride);return k}nx(k,F){const a={};Object.assign(a,z7());Object.assign(a,k);IA(this,a,F);g.kj(this.player,"captionssettingschanged")}yX(){!this.V&&this.loaded&&(g.BZ(this.D3,function(k,F){k.dispose();delete this.D3[F]},this),this.E3())}n$(k,F){switch(k){case "fontSize":if(isNaN(F))break;
k=g.Oz(F,-2,4);this.nx({fontSizeIncrement:k});return k;case "reload":F&&!this.V&&rH(this,this.D,!0);break;case "stickyLoading":F!==void 0&&this.B.W&&(g.nE(this.B)?H7(this,!!F):Jm(this,!!F));break;case "track":return giz(this,F);case "tracklist":return this.K?g.bb(g.a0(this.K.D,!(!F||!F.includeAsr)),a=>g.rO(a)):[];
case "translationLanguages":return this.K?this.K.X.map(a=>Object.assign({},a)):[];
case "sampleSubtitles":this.V||F===void 0||mN(this,!!F);break;case "sampleSubtitlesCustomized":this.V||mN(this,!!F,F);break;case "recommendedTranslationLanguages":return g.il();case "defaultTranslationSourceTrackIndices":return this.K?this.K.OO:[]}}getOptions(){const k="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.B.W&&k.push("stickyLoading");return k}cT(){let k=this.D;if(this.J.I9("captions")){if(this.B.A("html5_modify_caption_vss_logging"))return(k=this.videoData.VW??
null)?{cc:g.dGQ(k)}:{};if(k){let F=k.vssId;k.translationLanguage&&F&&(F=`t${F}.${g.hl(k)}`);return{cc:F}}}return{}}xS(){this.isSubtitlesOn()?(g.nE(this.B)?H7(this,!1):Jm(this,!1),QU(this),rH(this,null,!0)):this.ac()}ac(){const k=eJ(this)||!this.D?P7(this,!0):this.D;k&&this.Mp(k.vssId,"m");this.isSubtitlesOn()||rH(this,eJ(this)||!this.D?P7(this,!0):this.D,!0)}isSubtitlesOn(){return!!this.loaded&&!!this.D&&!eJ(this)}iI(){const k=eJ(this);Zf(this,k)?rH(this,this.getAudioTrack().D,!1):this.videoData.captionTracks.length&&
(this.loaded&&this.unload(),this.Id()&&(this.T=!1,this.D=null,this.K&&(this.K.dispose(),this.K=null)),this.iR()&&(k?rH(this,P7(this,!1),!1):this.load()))}d1(k){k&&(this.j={top:k.top,right:k.right,bottom:k.bottom,left:k.left,width:1-k.left-k.right,height:1-k.top-k.bottom},this.W.element.style.top=`${this.j.top*100}%`,this.W.element.style.left=`${this.j.left*100}%`,this.W.element.style.width=`${this.j.width*100}%`,this.W.element.style.height=`${this.j.height*100}%`,this.W.element.style.position="absolute",
k=u0z(this))&&(this.W.element.style.width=`${k.width}px`,this.W.element.style.height=`${k.height}px`)}onVideoDataChange(k,F){k==="newdata"&&(this.videoData=F,this.loaded&&this.unload(),this.T=!1,this.D=null,this.K&&(this.K.dispose(),this.K=null,g.kj(this.player,"captionschanged",{})),this.iR()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}gB(){const k=this.J.XX();k&&!k.wU()&&k.T();this.J.isFullscreen()?(this.V=this.TL=!0,this.loaded&&this.E8()):(this.TL=this.B.controlsType==="3",
this.V=V6k(this));rH(this,this.D)}PA(){const k=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;k&&g.zD(this.player,"innertubeCommand",k)}Qe(k,F,a){const V=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm;let M="";k&&(M=k.vssId,M=M.replace(V,""));let C="";k&&k.getId()&&(C=k.getId()||"");k&&k.getXtags()&&(k=k.getXtags(),k=k.replace(V,""),C=C.concat(`;${k}`));this.O==="HLS"&&(C="");this.J.Qe(F?M:"",F?C:"",a)}Mp(k,F){k=(k||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,
"");k.length>0&&this.J.Mp(k,F)}});})(_yt_player);
