(function(g){var window=this;'use strict';var RA=function(k){k.publish("autonavvisibility")},odZ=function(k,F){g.zD(k,"onAutonavCoundownStarted",F)},jJ=function(k){return k.isBackground()&&k.CJ()},ndz=function(k,F){F=F.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
k.j=F?.navigationEndpoint;F=F?.trackingParams;k.playButton&&F&&k.J.setTrackingParams(k.playButton.element,F)},E7=function(k){const F=W7(k);
var a=Math,V=a.min;var M=k.T?Date.now()-k.T:0;a=V.call(a,M,F);$w(k,Math.ceil((F-a)/1E3));F-a<=500&&k.D()?k.select(!0):k.D()&&k.X.start()},Nf=function(k){var F=k.J.Dy(!0,k.J.isFullscreen());
g.B(k.container.element,"ytp-autonav-endscreen-small-mode",k.NT(F));g.B(k.container.element,"ytp-autonav-endscreen-is-premium",!!k.suggestion&&!!k.suggestion.f8);g.B(k.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!k.J.xH());g.B(k.J.getRootNode(),"countdown-running",k.D());g.B(k.container.element,"ytp-player-content",k.J.xH());g.t4(k.overlay.element,{width:`${F.width}px`});if(!k.D()){k.J.xH()?$w(k,Math.round(W7(k)/1E3)):$w(k);F=!!k.suggestion&&!!k.suggestion.Hh;const a=k.J.xH()||!F;g.B(k.container.element,
"ytp-autonav-endscreen-upnext-alternative-header-only",!a&&F);g.B(k.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",a&&!F);k.C.Sd(k.J.xH());g.B(k.element,"ytp-enable-w2w-color-transitions",!!k.J.getVideoData()?.watchToWatchTransitionRenderer)}},$w=function(k,F=-1){k=k.V.Z3("ytp-autonav-endscreen-upnext-header");
g.q$(k);if(F>=0){F=String(F);const a="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],V="Up next in $SECONDS".indexOf(a);if(V>=0){k.appendChild(g.uv("Up next in $SECONDS".slice(0,V)));const M=g.nR("span");g.Ej(M,"ytp-autonav-endscreen-upnext-header-countdown-number");g.mm(M,F);k.appendChild(M);k.appendChild(g.uv("Up next in $SECONDS".slice(V+a.length)));return}}g.mm(k,"Up next")},W7=function(k){return k.J.isFullscreen()?(k=k.J.getVideoData()?.f2,k===-1||k===void 0?8E3:k):k.J.um()>=0?k.J.um():
g.o6(k.J.S().experiments,"autoplay_time")||1E4},Df=function(k,F){F=ugz(k,F);
var a=Math,V=a.min;var M=(0,g.L)()-k.T;a=V.call(a,M,F);F=F===0?1:Math.min(a/F,1);k.QX.setAttribute("stroke-dashoffset",`${-211*(F+1)}`);F>=1&&k.D()&&k.api.getPresentingPlayerType()!==3?k.select(!0):k.D()&&k.V.start()},ugz=function(k,F){return F?F:k.api.isFullscreen()?(k=k.api.getVideoData()?.f2,k===-1||k===void 0?8E3:k):k.api.um()>=0?k.api.um():g.o6(k.api.S().experiments,"autoplay_time")||1E4},i9=function(k){const F=k.xH();
F!==k.T&&(k.T=F,RA(k.player),k.T?(k.K!==k.D&&k.K.hide(),k.table.hide()):(k.K!==k.D&&k.K.show(),k.table.show()))},fk=function(k){return g.mH(k.player)&&k.V()&&!k.Z},zK=function(k){const F=k.xH();
F!==k.X&&(k.X=F,RA(k.player))},GK=function(k){return g.mH(k.player)&&k.V()&&!k.C},b9=function(k){const F=k.xH();
F!==k.D3&&(k.D3=F,RA(k.player))},KZm=function(k){k=k.S();
return k.Mw&&!k.aG&&!k.disableOrganicUi},qrm=function(k){const F=k.player.getVideoData();
if(!F||k.D===F.aG&&k.K===F.Dl)return!1;k.D=F.aG;k.K=F.Dl;return!0},gdz=function(k){k.player.Cv("endscreen");
var F=k.player.getVideoData();F=new g.rZ(Math.max((F.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});const a=new g.rZ(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});k.player.KL([F,a])};
g.f3.prototype.um=g.aH(9,function(){return this.app.um()});
g.pu.prototype.um=g.aH(8,function(){return this.getVideoData().UA});
g.iZ.prototype.iM=g.aH(7,function(k){this.eF().iM(k)});
g.uX.prototype.iM=g.aH(6,function(k){this.tG!==k&&(this.tG=k,this.R9())});
var TQz=class extends g.G{constructor(k){const F=k.S(),a=F.V;super({U:"a",G:"ytp-autonav-suggestion-card",L:{href:"{{url}}",target:a?F.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},Y:[{U:"div",mN:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],L:{style:"{{background}}"},Y:[{U:"div",L:{"aria-label":"{{timestamp}}"},mN:["ytp-autonav-timestamp"],EO:"{{duration}}"},
{U:"div",mN:["ytp-autonav-live-stamp"],EO:"Live"},{U:"div",mN:["ytp-autonav-upcoming-stamp"],EO:"Upcoming"},{U:"div",G:"ytp-autonav-list-overlay",Y:[{U:"div",G:"ytp-autonav-mix-text",EO:"Mix"},{U:"div",G:"ytp-autonav-mix-icon"}]}]},{U:"div",mN:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],EO:"{{title}}"},{U:"div",mN:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],EO:"{{author}}"},{U:"div",mN:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],
EO:"{{views_and_publish_time}}"}]});this.J=k;this.suggestion=null;this.D=a;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)}select(){this.J.eq(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Nj||void 0)&&this.J.logClick(this.element)}onClick(k){g.BV(k,this.J,this.D,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(k){switch(k.keyCode){case 13:case 32:k.defaultPrevented||(this.select(),k.preventDefault())}}};var wH=class extends g.G{constructor(k,F=!1){super({U:"div",G:"ytp-autonav-endscreen-countdown-overlay"});this.Jl=F;this.cancelCommand=this.j=void 0;this.T=0;this.container=new g.G({U:"div",G:"ytp-autonav-endscreen-countdown-container"});g.Q(this,this.container);this.container.rU(this.element);F=k.S();const a=F.V;this.J=k;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.N(k,"videodatachange",this.onVideoDataChange);this.V=new g.G({U:"div",G:"ytp-autonav-endscreen-upnext-container",
L:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},Y:[{U:"div",G:"ytp-autonav-endscreen-upnext-header"},{U:"div",G:"ytp-autonav-endscreen-upnext-alternative-header",EO:"{{autoplayAlternativeHeader}}"},{U:"a",G:"ytp-autonav-endscreen-link-container",L:{href:"{{url}}",target:a?F.X:""},Y:[{U:"div",G:"ytp-autonav-endscreen-upnext-thumbnail",L:{style:"{{background}}"},Y:[{U:"div",L:{"aria-label":"{{timestamp}}"},
mN:["ytp-autonav-timestamp"],EO:"{{duration}}"},{U:"div",mN:["ytp-autonav-live-stamp"],EO:"Live"},{U:"div",mN:["ytp-autonav-upcoming-stamp"],EO:"Upcoming"}]},{U:"div",G:"ytp-autonav-endscreen-video-info",Y:[{U:"div",G:"ytp-autonav-endscreen-premium-badge"},{U:"div",G:"ytp-autonav-endscreen-upnext-title",EO:"{{title}}"},{U:"div",G:"ytp-autonav-endscreen-upnext-author",EO:"{{author}}"},{U:"div",G:"ytp-autonav-view-and-date",EO:"{{views_and_publish_time}}"},{U:"div",G:"ytp-autonav-author-and-view",EO:"{{author_and_views}}"}]}]}]});
g.Q(this,this.V);this.V.rU(this.container.element);a||this.N(this.V.Z3("ytp-autonav-endscreen-link-container"),"click",this.OO);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.V.Z3("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.G({U:"div",G:"ytp-autonav-overlay"});g.Q(this,this.overlay);this.overlay.rU(this.container.element);this.C=new g.G({U:"div",G:"ytp-autonav-endscreen-button-container"});g.Q(this,this.C);this.C.rU(this.container.element);
this.cancelButton=new g.G({U:"button",mN:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],L:{"aria-label":"Cancel autoplay"},EO:"Cancel"});g.Q(this,this.cancelButton);this.cancelButton.rU(this.C.element);this.cancelButton.listen("click",this.QX,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.G({U:"a",mN:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
"ytp-autonav-endscreen-upnext-button-rounded"],L:{href:"{{url}}",role:"button","aria-label":"Play next video"},EO:"Play Now"});g.Q(this,this.playButton);this.playButton.rU(this.C.element);this.playButton.listen("click",this.OO,this);this.J.createServerVe(this.playButton.element,this.playButton,!0);(F=this.J.getVideoData())&&ndz(this,F);this.X=new g.La(()=>{E7(this)},500);
g.Q(this,this.X);this.D3();this.N(k,"autonavvisibility",this.D3);this.J.A("web_autonav_color_transition")&&(this.N(k,"autonavchange",this.VX),this.N(k,"onAutonavCoundownStarted",this.cA))}W(k){this.suggestion!==k&&(this.suggestion=k,g.ys(this.V,k),this.playButton.updateValue("url",this.suggestion.T8()),Nf(this))}D(){return this.T>0}Z(){this.D()||(this.T=Date.now(),E7(this),odZ(this.J,W7(this)),g.B(this.J.getRootNode(),"countdown-running",this.D()))}O(){this.K();E7(this);const k=this.V.Z3("ytp-autonav-endscreen-upnext-header");
k&&g.mm(k,"Up next")}K(){this.D()&&(this.X.stop(),this.T=0)}select(k=!1){this.J.nextVideo(!1,k);this.K()}OO(k){g.BV(k,this.J)&&(k.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):k.currentTarget===this.V.Z3("ytp-autonav-endscreen-link-container")&&(k=this.V.Z3("ytp-autonav-endscreen-link-container"),this.J.logVisibility(k,!0),this.J.logClick(k)),this.j?(g.zD(this.J,"innertubeCommand",this.j),this.K()):this.select())}QX(){this.J.logClick(this.cancelButton.element);g.nr(this.J,
!0);this.cancelCommand&&g.zD(this.J,"innertubeCommand",this.cancelCommand)}onVideoDataChange(k,F){ndz(this,F);this.cancelCommand=F.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}cA(k){if(this.J.getVideoData()?.watchToWatchTransitionRenderer){var F=this.J.getVideoData().watchToWatchTransitionRenderer;const a=F?.fromColorPaletteDark,V=F?.toColorPaletteDark;a&&V&&(F=this.element,F.style.setProperty("--w2w-start-background-color",
g.j4(a.surgeColor)),F.style.setProperty("--w2w-start-primary-text-color",g.j4(a.primaryTitleColor)),F.style.setProperty("--w2w-start-secondary-text-color",g.j4(a.secondaryTitleColor)),F.style.setProperty("--w2w-end-background-color",g.j4(V.surgeColor)),F.style.setProperty("--w2w-end-primary-text-color",g.j4(V.primaryTitleColor)),F.style.setProperty("--w2w-end-secondary-text-color",g.j4(V.secondaryTitleColor)),F.style.setProperty("--w2w-animation-duration",`${k}ms`));g.B(this.element,"ytp-w2w-animate",
!0)}}VX(k){this.J.A("web_autonav_color_transition")&&k!==2&&g.B(this.element,"ytp-w2w-animate",!1)}D3(){const k=this.J.xH();this.Jl&&this.Vm!==k&&this.Sd(k);Nf(this);this.J.logVisibility(this.container.element,k);this.J.logVisibility(this.cancelButton.element,k);this.J.logVisibility(this.V.Z3("ytp-autonav-endscreen-link-container"),k);this.J.logVisibility(this.playButton.element,k)}NT(k){return k.width<400||k.height<459}};var kN=class extends g.G{constructor(k,F){super({U:"div",mN:["html5-endscreen","ytp-player-content",F||"base-endscreen"]});this.created=!1;this.player=k}create(){this.created=!0}destroy(){this.created=!1}V(){return!1}xH(){return!1}j(){return!1}};var Fj=class extends g.G{constructor(k){super({U:"div",mN:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},Y:[{U:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{U:"span",G:"ytp-upnext-top",Y:[{U:"span",G:"ytp-upnext-header",EO:"Up Next"},{U:"span",G:"ytp-upnext-title",EO:"{{title}}"},{U:"span",G:"ytp-upnext-author",EO:"{{author}}"}]},{U:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},Y:[{U:"svg",L:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},Y:[{U:"circle",G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{U:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{U:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{U:"span",G:"ytp-upnext-bottom",Y:[{U:"span",G:"ytp-upnext-cancel"},
{U:"span",G:"ytp-upnext-paused",EO:"Autoplay is paused"}]}]});this.api=k;this.cancelButton=null;this.QX=this.Z3("ytp-svg-autoplay-ring");this.X=this.notification=this.V=this.suggestion=null;this.j=new g.La(this.C,5E3,this);this.T=0;var F=this.Z3("ytp-upnext-cancel");this.cancelButton=new g.G({U:"button",mN:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},EO:"Cancel"});g.Q(this,this.cancelButton);this.cancelButton.listen("click",this.OO,this);this.cancelButton.rU(F);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.Q(this,this.j);this.api.createClientVe(this.element,this,18788);F=this.Z3("ytp-upnext-autoplay-icon");this.N(F,"click",this.VX);this.api.createClientVe(F,this,115130);this.D3();this.N(k,"autonavvisibility",this.D3);this.N(k,"mdxnowautoplaying",this.cA);this.N(k,"mdxautoplaycanceled",this.Jl);g.B(this.element,"ytp-upnext-mobile",this.api.S().K)}C(){this.notification&&(this.j.stop(),this.Ar(this.X),this.X=null,this.notification.close(),
this.notification=null)}W(k){this.suggestion=k;g.ys(this,k,"hqdefault.jpg")}D3(){this.Sd(this.api.xH());this.api.logVisibility(this.element,this.api.xH());this.api.logVisibility(this.Z3("ytp-upnext-autoplay-icon"),this.api.xH());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.xH())}a5(){window.focus();this.C()}Z(k){this.D()||(g.wx("a11y-announce",`${"Up Next"} ${this.suggestion.title}`),this.T=(0,g.L)(),this.V=new g.La(()=>{Df(this,k)},25),Df(this,k),odZ(this.api,ugz(this,
k)));
g.fa(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}D(){return!!this.V}O(){this.K();this.T=(0,g.L)();Df(this);g.Dz(this.element,"ytp-upnext-autoplay-paused")}K(){this.D()&&(this.V.dispose(),this.V=null)}select(k=!1){if(this.api.S().A("autonav_notifications")&&k&&window.Notification&&typeof document.hasFocus==="function"){const F=Notification.permission;F==="default"?Notification.requestPermission():F!=="granted"||document.hasFocus()||(this.C(),this.notification=new Notification("Up Next",
{body:this.suggestion.title,icon:this.suggestion.kO()}),this.X=this.N(this.notification,"click",this.a5),this.j.start())}this.K();this.api.nextVideo(!1,k)}VX(k){!g.Iy(this.cancelButton.element,k.target)&&g.BV(k,this.api)&&(this.api.xH()&&this.api.logClick(this.Z3("ytp-upnext-autoplay-icon")),this.select())}OO(){this.api.xH()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.nr(this.api,!0)}cA(k){this.api.getPresentingPlayerType();this.show();this.Z(k)}Jl(){this.api.getPresentingPlayerType();
this.K();this.hide()}p6(){this.K();this.C();super.p6()}};var m_S=class extends kN{constructor(k){super(k,"autonav-endscreen");this.overlay=this.videoData=null;this.table=new g.G({U:"div",G:"ytp-suggestion-panel",Y:[{U:"div",mN:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],EO:"More videos"}]});this.X=new g.G({U:"div",G:"ytp-suggestions-container"});this.videos=[];this.O=null;this.T=this.W=!1;this.K=new wH(this.player);g.Q(this,this.K);this.K.rU(this.element);k.getVideoData().Dl?this.D=this.K:(this.D=new Fj(k),g.Ii(this.player,
this.D.element,4),g.Q(this,this.D));this.overlay=new g.G({U:"div",G:"ytp-autonav-overlay-cancelled-state"});g.Q(this,this.overlay);this.overlay.rU(this.element);this.Z=new g.Ms(this);g.Q(this,this.Z);g.Q(this,this.table);this.table.rU(this.element);this.table.show();g.Q(this,this.X);this.X.rU(this.table.element);this.hide()}create(){super.create();this.Z.N(this.player,"appresize",this.C);this.Z.N(this.player,"onVideoAreaChange",this.C);this.Z.N(this.player,"videodatachange",this.onVideoDataChange);
this.Z.N(this.player,"autonavchange",this.D3);this.Z.N(this.player,"onAutonavCancelled",this.OO);this.onVideoDataChange()}show(){super.show();(this.W||this.O&&this.O!==this.videoData.clientPlaybackNonce)&&g.nr(this.player,!1);g.mH(this.player)&&this.V()&&!this.O?(i9(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||jJ(this.player.BJ())&&this.player.A("web_player_pip_logging_fix")?this.D.select(!0):this.D.Z():this.videoData.autonavState===3&&this.D.O()):(g.nr(this.player,
!0),i9(this));this.C()}hide(){super.hide();this.D.O();i9(this)}C(){var k=this.player.Dy(!0,this.player.isFullscreen());i9(this);Nf(this.K);g.B(this.element,"ytp-autonav-cancelled-small-mode",this.NT(k));g.B(this.element,"ytp-autonav-cancelled-tiny-mode",this.Dv(k));g.B(this.element,"ytp-autonav-cancelled-mini-mode",k.width<=400||k.height<=360);this.overlay&&g.t4(this.overlay.element,{width:`${k.width}px`});if(!this.T)for(k=0;k<this.videos.length;k++)g.B(this.videos[k].element,"ytp-suggestion-card-with-margin",
k%2===1)}onVideoDataChange(){var k=this.player.getVideoData();if(this.videoData!==k&&k){this.videoData=k;k=this.videoData.suggestions;var F=this.videoData.I5();F&&(this.D.W(F),this.D!==this.K&&this.K.W(F));if(k&&k.length)for(let V=0;V<IYS.length;++V){var a=IYS[V];k&&k[a]&&(this.videos[V]=new TQz(this.player),F=this.videos[V],a=k[a],F.suggestion!==a&&(F.suggestion=a,g.ys(F,a)),g.Q(this,this.videos[V]),this.videos[V].rU(this.X.element))}this.C()}}D3(k){k===1?(this.W=!1,this.O=this.videoData.clientPlaybackNonce,
this.D.K(),this.Vm&&this.C()):(this.W=!0,this.xH()&&(k===2?this.D.Z():k===3&&this.D.O()))}OO(k){k?this.D3(1):(this.O=null,this.W=!1)}V(){return this.videoData.autonavState!==1}NT(k){return(k.width<910||k.height<459)&&!this.Dv(k)&&!(k.width<=400||k.height<=360)}Dv(k){return k.width<800&&!(k.width<=400||k.height<=360)}xH(){return this.Vm&&g.mH(this.player)&&this.V()&&!this.O}},IYS=[1,3,2,4];var SrQ=class extends kN{constructor(k){super(k,"videowall-endscreen");this.J=k;this.stills=[];this.Z=this.videoData=null;this.C=this.X=!1;this.D3=null;g.Dz(this.element,"modern-videowall-endscreen");this.K=new g.Ms(this);g.Q(this,this.K);this.T=new g.La(()=>{g.Dz(this.element,"ytp-show-tiles")},0);
g.Q(this,this.T);this.table=new g.eW({U:"div",G:"ytp-modern-endscreen-content"});g.Q(this,this.table);this.table.rU(this.element);k.getVideoData().Dl?this.D=new wH(k,!0):this.D=new Fj(k);g.Q(this,this.D);g.Ii(this.player,this.D.element,4);k.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var k=this.player.getVideoData();k&&(this.videoData=k);this.O();this.K.N(this.player,"appresize",this.O);this.K.N(this.player,"onVideoAreaChange",this.O);this.K.N(this.player,"videodatachange",
this.onVideoDataChange);this.K.N(this.player,"autonavchange",this.W);this.K.N(this.player,"onAutonavCancelled",this.OO);k=this.videoData.autonavState;k!==this.D3&&this.W(k);this.K.N(this.element,"transitionend",this.VX)}destroy(){this.K.K();g.zB(this.stills);this.stills=[];super.destroy();g.fa(this.element,"ytp-show-tiles");this.T.stop();this.D3=this.videoData.autonavState}V(){return this.videoData.autonavState!==1}show(){const k=this.Vm;super.show();g.fa(this.element,"ytp-show-tiles");this.player.S().K?
g.RK(this.T):this.T.start();(this.C||this.Z&&this.Z!==this.videoData.clientPlaybackNonce)&&g.nr(this.player,!1);fk(this)?(zK(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||jJ(this.player.BJ())&&this.player.A("web_player_pip_logging_fix")?this.D.select(!0):this.D.Z():this.videoData.autonavState===3&&this.D.O()):(g.nr(this.player,!0),zK(this));k!==this.Vm&&this.player.logVisibility(this.element,!0)}hide(){const k=this.Vm;super.hide();this.D.O();zK(this);k!==this.Vm&&this.player.logVisibility(this.element,
!1)}VX(k){k.target===this.element&&this.O()}O(){const k=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.I5()];if(k.length){var F=this.J.Dy(!0,this.J.isFullscreen()),a=Math.floor((F.width-64+16)/(g.Oz(F.width*.27,250,450)+16));F=Math.min(3,Math.floor((F.height-64)/((F.width-64-(a-1)*16)/a*.5625+70)));g.zX(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);g.Dz(this.element,`ytp-modern-endscreen-limit-rows-${F}`);
g.B(this.element,"ytp-modern-endscreen-single-item",a===1);g.B(this.element,"ytp-modern-endscreen-row-0",F===0);a=this.table.element;a.ariaLive="polite";this.D.W(this.videoData.I5());this.D instanceof wH&&Nf(this.D);g.B(this.element,"ytp-endscreen-takeover",fk(this));zK(this);F=0;a.ariaBusy="true";var V=k.length;for(let M=0;M<V;M++){const C=M%V;let X=this.stills[M];X||(X=new g.lKy(this.player),this.stills[M]=X,a.appendChild(X.element));g.JGb(X,k[C]);F++}this.stills.length=F}}onVideoDataChange(){const k=
this.player.getVideoData({playerType:1});this.videoData!==k&&(k?.I5()?(this.videoData=k,this.O()):this.player.K6("missg",{vid:k?.videoId||"",cpn:k?.clientPlaybackNonce||""}))}j(){return this.D.D()}W(k){k===1?(this.C=!1,this.Z=this.videoData.clientPlaybackNonce,this.D.K(),this.Vm&&this.O()):(this.C=!0,this.Vm&&fk(this)&&(k===2?this.D.Z():k===3&&this.D.O()))}OO(k){if(k){for(k=0;k<this.stills.length;k++)this.J.logVisibility(this.stills[k].element,!0);this.W(1)}else this.Z=null,this.C=!1;this.O()}xH(){return this.Vm&&
fk(this)}};var ZVS=class extends kN{constructor(k){super(k,"subscribecard-endscreen");this.D=new g.G({U:"div",G:"ytp-subscribe-card",Y:[{U:"img",G:"ytp-author-image",L:{src:"{{profilePicture}}"}},{U:"div",G:"ytp-subscribe-card-right",Y:[{U:"div",G:"ytp-author-name",EO:"{{author}}"},{U:"div",G:"html5-subscribe-button-container"}]}]});g.Q(this,this.D);this.D.rU(this.element);const F=k.getVideoData();this.subscribeButton=new g.ac("Subscribe",null,"Unsubscribe",null,!0,!1,F.Fd,F.subscribed,"trailer-endscreen",null,
k,!1);g.Q(this,this.subscribeButton);this.subscribeButton.rU(this.D.Z3("html5-subscribe-button-container"));this.N(k,"videodatachange",this.Nl);this.Nl();this.hide()}Nl(){const k=this.player.getVideoData();this.D.update({profilePicture:k.profilePicture,author:k.author});this.subscribeButton.channelId=k.Fd;var F=this.subscribeButton;k.subscribed?F.D():F.K()}};var eD8=class extends g.G{constructor(k){const F=k.S(),a=g.GC||g.gO?{style:"will-change: opacity"}:void 0,V=F.V,M=["ytp-videowall-still"];F.K&&M.push("ytp-videowall-show-text");super({U:"a",mN:M,L:{href:"{{url}}",target:V?F.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},Y:[{U:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{U:"span",G:"ytp-videowall-still-info",L:{"aria-hidden":"true"},Y:[{U:"span",G:"ytp-videowall-still-info-bg",
Y:[{U:"span",G:"ytp-videowall-still-info-content",L:a,Y:[{U:"span",G:"ytp-videowall-still-info-title",EO:"{{title}}"},{U:"span",G:"ytp-videowall-still-info-author",EO:"{{author_and_views}}"},{U:"span",G:"ytp-videowall-still-info-live",EO:"Live"},{U:"span",G:"ytp-videowall-still-info-duration",EO:"{{duration}}"}]}]}]},{U:"span",mN:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:{"aria-hidden":"true"},Y:[{U:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{U:"span",
G:"ytp-videowall-still-listlabel-length",Y:[" (",{U:"span",EO:"{{playlist_length}}"},")"]}]},{U:"span",mN:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],L:{"aria-hidden":"true"},Y:[{U:"span",G:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{U:"span",G:"ytp-videowall-still-listlabel-length",EO:" (50+)"}]}]});this.suggestion=null;this.K=V;this.api=k;this.D=new g.Ms(this);g.Q(this,this.D);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.D.N(k,"videodatachange",
this.onVideoDataChange);k.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.eq(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Nj||void 0)&&this.api.logClick(this.element)}onClick(k){if(g.w_(this.api.S())&&this.api.A("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let F=this.suggestion.T8();const a={};g.gZ(this.api,a);F=g.uS(F,a);g.Yj(F,this.api,k)}else g.BV(k,this.api,
this.K,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(k){switch(k.keyCode){case 13:case 32:k.defaultPrevented||(this.select(),k.preventDefault())}}onVideoDataChange(){const k=this.api.getVideoData(),F=this.api.S();this.K=k.Ix?!1:F.V}};var d_z=class extends kN{constructor(k){super(k,"videowall-endscreen");this.J=k;this.Z=0;this.stills=[];this.C=this.videoData=null;this.T=this.D3=!1;this.OO=null;this.O=new g.Ms(this);g.Q(this,this.O);this.W=new g.La(()=>{g.Dz(this.element,"ytp-show-tiles")},0);
g.Q(this,this.W);var F=new g.G({U:"button",mN:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},Y:[g.XL()]});g.Q(this,F);F.rU(this.element);F.listen("click",this.cA,this);this.table=new g.eW({U:"div",G:"ytp-endscreen-content"});g.Q(this,this.table);this.table.rU(this.element);F=new g.G({U:"button",mN:["ytp-button","ytp-endscreen-next"],L:{"aria-label":"Next"},Y:[g.Up()]});g.Q(this,F);F.rU(this.element);F.listen("click",this.QX,this);k.getVideoData().Dl?this.D=new wH(k,!0):this.D=
new Fj(k);g.Q(this,this.D);g.Ii(this.player,this.D.element,4);k.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var k=this.player.getVideoData();k&&(this.videoData=k);this.K();this.O.N(this.player,"appresize",this.K);this.O.N(this.player,"onVideoAreaChange",this.K);this.O.N(this.player,"videodatachange",this.onVideoDataChange);this.O.N(this.player,"autonavchange",this.X);this.O.N(this.player,"onAutonavCancelled",this.VX);k=this.videoData.autonavState;k!==this.OO&&this.X(k);
this.O.N(this.element,"transitionend",this.Jl)}destroy(){this.O.K();g.zB(this.stills);this.stills=[];super.destroy();g.fa(this.element,"ytp-show-tiles");this.W.stop();this.OO=this.videoData.autonavState}V(){return this.videoData.autonavState!==1}show(){const k=this.Vm;super.show();g.fa(this.element,"ytp-show-tiles");this.player.S().K?g.RK(this.W):this.W.start();(this.T||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.nr(this.player,!1);GK(this)?(b9(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||jJ(this.player.BJ())&&this.player.A("web_player_pip_logging_fix")?this.D.select(!0):this.D.Z():this.videoData.autonavState===3&&this.D.O()):(g.nr(this.player,!0),b9(this));k!==this.Vm&&this.player.logVisibility(this.element,!0)}hide(){const k=this.Vm;super.hide();this.D.O();b9(this);k!==this.Vm&&this.player.logVisibility(this.element,!1)}Jl(k){k.target===this.element&&this.K()}K(){var k=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.I5()];if(k.length){g.Dz(this.element,
"ytp-endscreen-paginate");var F=this.J.Dy(!0,this.J.isFullscreen()),a=g.Md(this.J);a&&(a=a.Ve()?48:32,F.width-=a*2);var V=F.width/F.height,M=96/54,C=a=2,X=Math.max(F.width/96,2),U=Math.max(F.height/54,2),y=k.length;var n=y*4;for(n-=4;n>0&&(a<X||C<U);){var u=a/2,K=C/2,q=a<=X-2&&n>=K*4,T=C<=U-2&&n>=u*4;if((u+1)/K*M/V>V/(u/(K+1)*M)&&T)n-=u*4,C+=2;else if(q)n-=K*4,a+=2;else if(T)n-=u*4,C+=2;else break}M=!1;n>=12&&y*4-n<=6&&(C>=4||a>=4)&&(M=!0);n=a*96;X=C*54;V=n/X<V?F.height/X:F.width/n;V=Math.min(V,2);
n=Math.floor(Math.min(F.width,n*V));X=Math.floor(Math.min(F.height,X*V));F=this.table.element;F.ariaLive="polite";g.ws(F,n,X);g.t4(F,{marginLeft:`${n/-2}px`,marginTop:`${X/-2}px`});this.D.W(this.videoData.I5());this.D instanceof wH&&Nf(this.D);g.B(this.element,"ytp-endscreen-takeover",GK(this));b9(this);n+=4;X+=4;V=0;F.ariaBusy="true";for(U=0;U<a;U++)for(u=0;u<C;u++)if(q=V,T=0,M&&U>=a-2&&u>=C-2?T=1:u%2===0&&U%2===0&&(u<2&&U<2?u===0&&U===0&&(T=2):T=2),q=g.lL(q+this.Z,y),T!==0){K=this.stills[V];K||
(K=new eD8(this.player),this.stills[V]=K,F.appendChild(K.element));var S=Math.floor(X*u/C);const J=Math.floor(n*U/a),x=Math.floor(X*(u+T)/C)-S-4,O=Math.floor(n*(U+T)/a)-J-4;g.N$(K.element,J,S);g.ws(K.element,O,x);g.t4(K.element,"transitionDelay",(u+U)/20+"s");g.B(K.element,"ytp-videowall-still-mini",T===1);g.B(K.element,"ytp-videowall-still-large",T>2);T=Math.max(O,x);g.B(K.element,"ytp-videowall-still-round-large",T>=256);g.B(K.element,"ytp-videowall-still-round-medium",T>96&&T<256);g.B(K.element,
"ytp-videowall-still-round-small",T<=96);q=k[q];K.suggestion!==q&&(K.suggestion=q,T=K.api.S(),S=g.Np(K.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.ys(K,q,S),g.w_(T)&&!K.api.A("web_player_log_click_before_generating_ve_conversion_params")&&(T=q.T8(),S={},g.wE(K.api,"addEmbedsConversionTrackingParams",[S]),T=g.uS(T,S),K.updateValue("url",T)),(q=(q=q.sessionData)&&q.itct)&&K.api.setTrackingParams(K.element,q));V++}F.ariaBusy="false";g.B(this.element,"ytp-endscreen-paginate",
V<y);for(k=this.stills.length-1;k>=V;k--)a=this.stills[k],g.TJ(a.element),g.f0(a);this.stills.length=V}}onVideoDataChange(){const k=this.player.getVideoData({playerType:1});this.videoData!==k&&(k?.I5()?(this.Z=0,this.videoData=k,this.K()):this.player.K6("missg",{vid:k?.videoId||"",cpn:k?.clientPlaybackNonce||""}))}QX(){this.Z+=this.stills.length;this.K()}cA(){this.Z-=this.stills.length;this.K()}j(){return this.D.D()}X(k){k===1?(this.T=!1,this.C=this.videoData.clientPlaybackNonce,this.D.K(),this.Vm&&
this.K()):(this.T=!0,this.Vm&&GK(this)&&(k===2?this.D.Z():k===3&&this.D.O()))}VX(k){if(k){for(k=0;k<this.stills.length;k++)this.J.logVisibility(this.stills[k].element,!0);this.X(1)}else this.C=null,this.T=!1;this.K()}xH(){return this.Vm&&GK(this)}};var P7m=class extends g.G{constructor(k){super({U:"button",mN:["ytp-watch-on-youtube-button","ytp-button"],EO:"{{content}}"});this.J=k;this.buttonType=this.buttonType=1;this.D();this.buttonType===2&&g.Dz(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.D);this.Sd(!0)}D(){let k,F;switch(this.buttonType){case 1:k="Watch again on YouTube";F=156915;break;case 2:k="Continue watching on YouTube";F=156942;break;default:k="Continue watching on YouTube",
F=156942}this.update({content:k});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,F)}onClick(k){this.J.A("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.Yj(this.getVideoUrl(),this.J,k);this.J.A("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)}getVideoUrl(){var k=!0;switch(this.buttonType){case 1:k=!0;break;case 2:k=!1}k=this.J.getVideoUrl(k,!1,!1,!0);const F=
this.J.S();if(g.w_(F)){const a={};g.w_(F)&&g.wE(this.J,"addEmbedsConversionTrackingParams",[a]);k=g.uS(k,a)}return k}logVisibility(){this.J.logVisibility(this.element,this.Vm&&this.I5)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}Ij(k){super.Ij(k);this.logVisibility()}};var HVR=class extends kN{constructor(k){super(k,"watch-again-on-youtube-endscreen");this.watchButton=new P7m(k);g.Q(this,this.watchButton);this.watchButton.rU(this.element);g.Khp(k)&&(this.D=new g.ICX(k),g.Q(this,this.D),this.K=new g.G({U:"div",mN:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],L:{tabIndex:"-1"},Y:[this.D]}),g.Q(this,this.K),this.D.rU(this.K.element),this.K.rU(this.element));k.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.D?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();const F=this.K;if(F){var k=this.D.hasSuggestions();g.B(this.element,"ytp-shorts-branded-ui",k);k?F.show():F.hide()}g.Md(this.player)?.iM(!0);this.player.logVisibility(this.element,!0);this.watchButton.Ij(!0)}}hide(){super.hide();g.Md(this.player)?.iM(!1);this.player.logVisibility(this.element,!1);this.watchButton.Ij(!1)}};g.dp("endscreen",class extends g.ZH{constructor(k){super(k);this.endScreen=null;this.D=this.K=this.O=!1;this.listeners=new g.Ms(this);g.Q(this,this.listeners);const F=k.S();k.isEmbedsShortsMode()?this.endScreen=new HVR(k):KZm(k)?(this.O=!0,qrm(this),this.D?this.endScreen=new m_S(k):F.A("delhi_modern_endscreen")?this.endScreen=new SrQ(k):this.endScreen=new d_z(k)):F.aG?this.endScreen=new ZVS(k):this.endScreen=new kN(k);g.Q(this,this.endScreen);g.Ii(k,this.endScreen.element,4);gdz(this);this.listeners.N(k,
"videodatachange",this.onVideoDataChange,this);this.listeners.N(k,g.oO("endscreen"),a=>{this.onCueRangeEnter(a)});
this.listeners.N(k,g.nX("endscreen"),a=>{this.onCueRangeExit(a)})}iR(){var k=this.player.getVideoData();
const F=k.mutedAutoplay&&(k.limitedPlaybackDurationInSeconds>0||k.endSeconds>0||k.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!F)return!0;var a=!(!k?.I5()&&!k?.suggestions?.length);a=!KZm(this.player)||a;k=k.F7;const V=this.player.u6();return a&&!k&&!V&&!F}xH(){return this.endScreen.xH()}UV(){return this.xH()?this.endScreen.j():!1}p6(){this.player.Cv("endscreen");super.p6()}load(){{const a=this.player.getVideoData(),V=a.transitionEndpointAtEndOfStream;if(V&&V.videoId){var k=
this.player.cB().cO.get("heartbeat");var F=a.I5();!F||V.videoId!==F.videoId||a.Jp?(this.player.eq(V.videoId,void 0,void 0,!0,!0,V),k&&k.oS("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),k=!0):k=!1}else k=!1}k||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(k){this.iR()&&(this.endScreen.created||this.endScreen.create(),k.getId()==="load"&&this.load())}onCueRangeExit(k){k.getId()===
"load"&&this.loaded&&this.unload()}onVideoDataChange(){gdz(this);this.O&&qrm(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.D?this.endScreen=new m_S(this.player):this.endScreen=new d_z(this.player),g.Q(this,this.endScreen),g.Ii(this.player,this.endScreen.element,4))}});})(_yt_player);
